### ISSUE TITLE
Folder menu is not visible from Webgui / no search entries when folders enabled

### ISSUE THREAD

**Issue by vmario89** [jsuto/piler#100]
Hi,

the route /index.php?route=folder/list can be accessed manually, but is hidden from GUI, even when enabled in piler.conf, manticore.conf and config-site.php

is there any trick to add this as a sub menu button? otherwise i need to use a bookmark to access

additionally there's a bug with folders: when enabled in config-site.php, existing mails are not shown. The search result is ALWAYS empty. as soon as i set $config['ENABLE_FOLDER_RESTRICTIONS'] = 0; it works again

**Comment by vmario89** [comment]
i dont unterstand the concept of folders. When adding a folder as admin user, it works. When logging in as auditor then, the created folder is not visible. When trying to add a new folder a auditor, this fails

creating a new folder als regular user works. 

as soons there is one directory existing, the search result view seems to work properly again

**Comment by vmario89** [comment]
the search function cannot search for folders

**Comment by vmario89** [comment]
i will deactivate that function again. It would be useful to hide that menu when folder option is disabled. in default state (disabled), the following is still seen by admin user:

![grafik](https://github.com/user-attachments/assets/4385a226-66ac-47ed-8162-dace97d824c8)

thats the reason i started to play with the folder feature

**Comment by vmario89** [comment]
created folders cannot be deleted again. the gui does not return an error. also piler service has no log output about it

**Comment by vmario89** [comment]
maybe some helpul log line from nginx:
`2024/07/24 10:16:37 [error] 46511#46511: *1470 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "folder_id" in /mnt/storagespace/piler/www/model/folder/folder.php on line 214" while reading response header from upstream, client: 192.168.16.201, server: myhost.de, request: "POST /message.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.3-fpm.sock:", host: "myhost.de", referrer: "https://myhost.de/search.php"`

**Comment by jsuto** [comment]
Well, the folder feature is not a well thought out one, and I got different conflicting requests, so I've decided not to work on it any longer. I suggest not to use it.
