### ISSUE TITLE
[FEATURE] Option to view an email in fullscreen/dedicated window

### ISSUE THREAD

**Issue by vmario89** [jsuto/piler#103]
Hi,
just a a little feature which. The view pane below is to small to have a good view on the content. would be good to have a vertical split pane or fullscreen popup window or creating a new tab with the mail content

**Comment by jsuto** [comment]
Well, have you tried to resize the two horizontal panes? Btw. there was a poll about the layout, and though there were few votes only, people voted to keep the current layout.

**Comment by jsuto** [comment]
Try the master branch, and add the following to config-site.php:

```
$config['PREVIEW_PANE'] = 0;
```

**Comment by vmario89** [comment]
thank you! that commit works fine!
for sure i tried resizing but for my feeling it was not enough space to have a clear eye on the content
