### ISSUE TITLE
[FEATURE] Change defaults for $config['SITE_NAME']

### ISSUE THREAD

**Issue by dilyanpalauzov** [jsuto/piler#108]
Currently the default in config.site is
```
$config['SITE_NAME'] = 'piler.example.com';
```
this means user always have to change it explicitly during installation.

I propose to change the default to
```
$config['SITE_NAME'] = $SERVER['SERVER_NAME']; // e.g. piler.example.com 
```

This way often users will have good defaults and will not need to change them.

**Comment by jsuto** [comment]
I think such change would have side effects. The $_SERVER array is available only if the script is run via php-fpm, ie. the webserver. Eg. manticore.conf would emit a warning which would interfere the printed config that manticore reads.

**Comment by jsuto** [comment]
The SITE_NAME cannot be empty, it's used elsewhere, too. I've fixed the SITE_URL references to use the same scheme.
