### ISSUE TITLE
[BUG] Docker: searchd OOM

### ISSUE THREAD

**Issue by otbutz** [jsuto/piler#109]
**Describe the bug**

The memory constraints of the default `docker-compose.yaml` trigger an OOM kill of the searchd process in the container under high load:

```
Jul 25 19:13:09 piler kernel: Tasks state (memory values in pages):
Jul 25 19:13:09 piler kernel: [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
Jul 25 19:13:09 piler kernel: [  18052]     0 18052      276        1    32768        0             0 docker-init
Jul 25 19:13:09 piler kernel: [  18090]     0 18090     1241      892    49152        0             0 start.sh
Jul 25 19:13:09 piler kernel: [  18105]     0 18105      950      425    49152        0             0 cron
Jul 25 19:13:09 piler kernel: [  18115]     0 18115    56099     1987   139264        0             0 php-fpm8.3
Jul 25 19:13:09 piler kernel: [  18116]    33 18116    56192     5681   167936        0             0 php-fpm8.3
Jul 25 19:13:09 piler kernel: [  18117]    33 18117    56223     5887   172032        0             0 php-fpm8.3
Jul 25 19:13:09 piler kernel: [  18130]     0 18130     2787      262    57344        0             0 nginx
Jul 25 19:13:09 piler kernel: [  18131]    33 18131     2875      523    57344        0             0 nginx
Jul 25 19:13:09 piler kernel: [  18132]    33 18132     2961     1043    57344        0             0 nginx
Jul 25 19:13:09 piler kernel: [  18133]    33 18133     2962     1015    57344        0             0 nginx
Jul 25 19:13:09 piler kernel: [  18134]    33 18134     2875      574    57344        0             0 nginx
Jul 25 19:13:09 piler kernel: [  18136]   100 18136    38124      502    69632        0             0 rsyslogd
Jul 25 19:13:09 piler kernel: [  18147]  1001 18147    14289     1003   106496        0             0 searchd
Jul 25 19:13:09 piler kernel: [  18148]  1001 18148   150479    72245   847872        0             0 searchd
Jul 25 19:13:09 piler kernel: [  18162]  1001 18162     3839      848    57344        0             0 piler-smtp
Jul 25 19:13:09 piler kernel: [  18164]  1001 18164     2405      234    45056        0             0 piler
Jul 25 19:13:09 piler kernel: [  18165]  1001 18165     2405      419    49152        0             0 piler
Jul 25 19:13:09 piler kernel: [  18166]  1001 18166     2405      441    49152        0             0 piler
Jul 25 19:13:09 piler kernel: [  18167]     0 18167      672      195    40960        0             0 sleep
Jul 25 19:13:09 piler kernel: [  18284]     0 18284     1145      803    49152        0             0 bash
Jul 25 19:13:09 piler kernel: [  18293]     0 18293    11353    10342   126976        0             0 pilerimport
Jul 25 19:13:09 piler kernel: [  49194]    33 49194    56187     5720   167936        0             0 php-fpm8.3
Jul 25 19:13:09 piler kernel: oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=a219f1fe1666db1c34148caf1a56eba37275fa3f6a959503595a2b618630b4ef,mems_allowed=0,oom_memcg=/docker/a219f1fe1666db1c34148caf1a56eba37275fa3f6a959503595a2b618630b4ef,task_memcg=/docker/a219f1fe1666db1c34148caf1a56eba37275fa3f6a959503595a2b618630b4ef,task=searchd,pid=18148,uid=1001
Jul 25 19:13:09 piler kernel: Memory cgroup out of memory: Killed process 18148 (searchd) total-vm:601916kB, anon-rss:278328kB, file-rss:10648kB, shmem-rss:4kB, UID:1001 pgtables:828kB oom_score_adj:0
```

**To Reproduce**
1. Run the piler containers
2. Run `pilerimport` against a large folder of EML files
3. wait for the OOM killer

**Expected behavior**
We should either lift the memory constraints or even better: use a proper service manager like e.g tini or S6 inside the container which would restart the service or the container itself

**Piler version:**
 - 1.4.6

**Comment by jsuto** [comment]
Could you be more specific with the "large folder of emails files"? Do you have a single dir with millions of files or several subdirectories, etc.

Anyway, you are free to increase the memory limit of the piler container, assuming you use the docker-compose.yaml file. 512 MB is good enough for testing actually. For production deployments you need more, but it's hard to find a good number that suits all deployments, so it's up to your judgement. Let me know how much memory seems to be fine for you.

**Comment by otbutz** [comment]
I think the limit isn't the real problem here. It's rather that the container ends up in a half dead state. It would be good if the piler container has a whole would stop if one of it's services crashes.

e.g. https://github.com/krallin/tini

**Comment by jsuto** [comment]
OK, I get it. I've refactored docker compose to use manticore's image instead of installing it to the piler image. The piler daemons use less memory than manticore, so it's less chance to end up in OOM. Btw. docker compose uses ```init: true``` ie. it already uses tiny.

**Comment by jsuto** [comment]
One small caveat. The piler-smtp daemon is configured to use max. ~500 MB memory, so if you expect lots of huge emails are coming in parallel, then increase the memory limit to 1024M. I encourage you to test the docker-compose.yaml on the master branch (and be sure to use sutoj/piler:test until the release of 1.4.7, because 1.4.6 has searchd running in the piler container).

**Comment by otbutz** [comment]
Will do. Right now the import is chugging along nicely and I don't want to interrupt it :stuck_out_tongue_winking_eye:

**Comment by otbutz** [comment]
Do I need to change the hostname for manticore somewhere in the configs? Something like `127.0.0.1` won't work after moving to a separate container.

PS: I think you can remove `init: true` from the manticore container.

**Comment by jsuto** [comment]
Yes, fix it at 2 places:

/etc/piler/piler.conf:

```
sphxhost=manticore
```
/etc/piler/config-site.php:

```
$config['SPHINX_HOSTNAME'] = 'manticore:9306';
$config['SPHINX_HOSTNAME_READONLY'] = 'manticore:9307'
```

Btw. why remove ```init:true``` from the manticore container?

**Comment by otbutz** [comment]
Thanks! The should be added to the future 1.4.7 release notes.

> Btw. why remove `init:true` from the manticore container?

Not required by the upstream image: https://hub.docker.com/r/manticoresearch/manticore/

**Comment by jsuto** [comment]
OK, I'll do.
