### ISSUE TITLE
[FEATURE]  add environment variable for subpath

### ISSUE THREAD

**Issue by th-2021** [jsuto/piler#115]
According to the RELEASE-NOTES one has to make some edits to config files (one within the container) to config a subpath. Allowing to use an environment variable would simplify the setup.

**Comment by jsuto** [comment]
Let's say we create the PATH_PREFIX env variable. How would it work?

**Comment by th-2021** [comment]
It's available via getenv() in php. So config.site could use it.

The nginx configuration would need to be changed during start.sh, e.g.
add XYZZY as subpath and replace it with the environment variable (or
remove it, if empty).

Not sure how to deal with it in js. I have an example with Angular,
where base path is set to "./". Reference:
https://symflower.com/en/company/blog/2021/path-independent-angular/

Does this help?

Am 26.07.2024 um 15:38 schrieb jsuto:

**Comment by jsuto** [comment]
getenv() won't work when a php script is called from php-fpm. Also I don't like it, and I don't think that the majority of piler users really need the subpath feature.

**Comment by th-2021** [comment]
How are the users deploying piler? On a separate server?
I have consolidated all my apps with subpath on a single server.

Am 26. Juli 2024 17:59:03 MESZ schrieb jsuto ***@***.***>:

**Comment by jsuto** [comment]
Yes, that's the typical scenario. Imagine your single server has an issue, then all your emails are gone. Both your inbox and your archive. At least that's not acceptable with a decent disaster recovery plan. Also you don't put all your eggs to a single basket.

Btw. even though you have a single server, you can still use dedicated hostnames for each service.

**Comment by th-2021** [comment]
My server is part of a ha cluster with kubernetes. So spof is not an issue.Am 26.07.2024 19:31 schrieb jsuto ***@***.***>:
Yes, that's the typical scenario. Imagine your single server has an issue, then all your emails are gone. Both your inbox and your archive. At least that's not acceptable with a decent disaster recovery plan. Also you don't put all your eggs to a single basket.
Btw. even though you have a single server, you can still use dedicated hostnames for each service.

**Comment by jsuto** [comment]
Right. With kubernetes you can have a dedicated hostname. If that's not feasible for some legit reason, the subpath feature has been implemented. So the bottomline is that I don't plan this feature for the moment, sorry,
