### ISSUE TITLE
Missing archiving rules for CC/BCC

### ISSUE THREAD

**Issue by vmario89** [jsuto/piler#119]
HI,

i am watching a lot of github repositories (doing this privately on my business server with another mail domain). In case something happens there, i get a notification from github by mail. My own email address is not in the to: field, but in the cc: field. The issue is now that the to: field is always populated with mail addresses like "reply+ABK6YXZURPQEWAOD2K7KAXOEWHWM7EVBNHHJBKASOU@reply.github.com" and so it flows into the mail archive - but i want to omit this. 

I could add a rule to filter reply.github.com but the better option would be to have a new filter for CC/BCC fields

**Comment by jsuto** [comment]
I'm not sure if I got this right, but if you created an exclusion rule using the Cc address (ie. your own email address), then all of your emails would be discarded (since it contains your email address). Wouldn't it be better to exclude such github emails where the From: address is notifications@github.com?

**Comment by vmario89** [comment]
in my case this would make a lot of extra work because i have had to create an exclusion rule for such mail addresses like notifcations@github.com

i have a mailbox which is included in my mail server and i want to exclude it from piler totally. As soon as it is CC'ed or BCC'ed in will get fetched by piler because i can only set a filter to to exclude when this mailbox was from: or to:

**Comment by vmario89** [comment]
might be my own fault because maybe i need to rethink: will i do it correct if i set special domains in the admin backend and configre pilerconf to use archive_only_mydomains=1 ?

**Comment by jsuto** [comment]
Not necessarily. The "To:" field in the archiving rules section includes the Cc addresses as well. When you run pilertest on a message, then it prints all To/Cc addresses to the recipients section. So if your usuall address is user@example.com, but you receive these unwanted emails (from the archive's perspective) to user@subdomain.example.com, then simply create an archiving rule as ```To: user@subdomain.example.com```, even if it's the Cc: address actually. I'll update the text from "To" to "To/Cc" on the rule admin page to make it clear.

**Comment by vmario89** [comment]
thanks for the hint with pilertest. i checked this 

Thunderbird reads the mail and shows the to: field with my address (i marked it red and obfuscated it)
![grafik](https://github.com/user-attachments/assets/70b668b7-5ad9-4816-971e-a1ef5083d1d2)

the pilertest does not recognise this addresse from *.eml file:

`pilertest -c /etc/piler/piler.conf -m Re-jsuto-piler-BUG-Docker-searchd-OOM-Issue-109-.eml`

i changed the address to "user@example.com" in the following output:

```
locale: C.UTF-8
version: 1.4.6
parsing...
post parsing...
message-id: <jsuto/piler/issues/109/2252007730@github.com> / 99995e6b32a980a1c600751db02eaee60086dabbedd69b63b19058cdf8f6cf70
from: *jsuto notifications@github.com notifications github com  (github.com)*
sender: * ()*
to: *jsuto piler piler@noreply.github.com piler noreply github com subscribed subscribed@noreply.github.com subscribed noreply github com  (noreply.github.com )*
journal recipients: **
reference: *<jsuto/piler/issues/109@github.com>*
subject: *Re: [jsuto/piler] [BUG] Docker: searchd OOM (Issue #109)*
body: *OK I get it I ve refactored docker compose to use manticore s image instead of installing it to the piler image The piler daemons use less memory than manticore so it s less chance to end up in OOM Btw docker compose uses init true ie it already uses tiny - Reply to this email directly or view it on GitHub __URL__githubXcom issuecomment-2252007730 You are receiving this because you are subscribed to this thread Message ID jsuto piler issues 109 2252007730XgithubXcom OK I get it I ve refactored docker compose to use manticore s image instead of installing it to the piler image The piler daemons use less memory than manticore so it s less chance to end up in OOM Btw docker compose uses init true ie it already uses tiny q Reply to this email directly view it on GitHub or unsubscribe You are receiving this because you are subscribed to this thread Message ID jsuto piler issues 109 2252007730 @ github com @context __URL__schemaXorg  @type EmailMessage potentialAction @type ViewAction target __URL__githubXcom issuecomment-2252007730 url __URL__githubXcom issuecomment-2252007730 name View Issue description View this Issue on GitHub publisher @type Organization name GitHub url __URL__githubXcom  *
sent: 1721972137, delivered-date: 0
hdr len: 3872
body digest: 3dac51fd906be04e4863fe31e2fb98475cc88126958986267039b45b79491fd0
rules check: (null)
folder: 0
retention period: 2037332137 (3650 days)
attachments:
direction: 0
spam: 0
1st received line: Received: from localhost (localhost [127.0.0.1])	by mail.eridur.de (Postfix) with ESMTP id 3320A24383E	for <user@example.com>; Fri, 26 Jul 2024 07:35:42 +0200 (CEST)
NOT IN mydomains

```

i think piler should look into the field "for" which reveals the "to" address in this case

The header of my example mail are:
```

Received: from localhost (localhost [127.0.0.1])
	by mail.another.server.de (Postfix) with ESMTP id 3320A24383E
	for <user@example.com>; Fri, 26 Jul 2024 07:35:42 +0200 (CEST)
DKIM-Filter: OpenDKIM Filter v2.11.0 mail.eridur.de 3320A24383E
Authentication-Results: mail.eridur.de;
	dkim=pass (1024-bit key, unprotected) header.d=github.com header.i=@github.com header.a=rsa-sha256 header.s=smtpapi header.b=NHGiIlLD
X-Virus-Scanned: amavis at example.com
Received: from mail.eridur.de ([127.0.0.1])
 by localhost (mail.eridur.de [127.0.0.1]) (amavis, port 10024) with ESMTP
 id us_9_0sch1rb for <user@example.com>;
 Fri, 26 Jul 2024 07:35:40 +0200 (CEST)
Received-SPF: Pass (mailfrom) identity=mailfrom; client-ip=167.89.101.201; helo=o10.sgmail.github.com; envelope-from=bounces+848413-a6fc-opensource=REDACTED; receiver=example.com
Received: from o10.sgmail.github.com (o10.sgmail.github.com [167.89.101.201])
	by mail.anotherserver.de (Postfix) with ESMTPS
	for <user@example.com>; Fri, 26 Jul 2024 07:35:40 +0200 (CEST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	h=from:in-reply-to:references:subject:mime-version:content-type:
	content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:list-unsubscribe-post:
	reply-to:to:cc:cc:content-type:from:subject:to;
	s=smtpapi; bh=dA4FduNXodYHtUxd7Lqr5eYomhTDQgF/DU2/qOgfS3g=;
	b=NHGiIlLDanDtVrYCWwIfTr8qCLVAOgHr1gOvN+Z88KqqoKtttnod0zDpdZSQQJ55Ypt6
	lNKie6ci8JNoVJ7t1LBYhBTBKPU+TletRRu8xHMVbmjGOmzNnqgwtpW7mn1E96zJAyHnNT
	cyDQb05dt2jo/GCXEHXPsmiopSBmx/31M=
Received: by recvd-957c9746c-vhxqc with SMTP id recvd-957c9746c-vhxqc-1-66A335A9-F
	2024-07-26 05:35:37.937435803 +0000 UTC m=+2464660.373706413
Received: from out-18.smtp.github.com (unknown)
	by geopod-ismtpd-31 (SG)
	with ESMTP id CylMpVzjR3GayrIK0IlS_Q
	for <user@example.com>;
	Fri, 26 Jul 2024 05:35:37.912 +0000 (UTC)
Received: from github.com (hubbernetes-node-a067960.va3-iad.github.net [10.48.124.15])
	by smtp.github.com (Postfix) with ESMTPA id CE254E0847
	for <user@example.com>; Thu, 25 Jul 2024 22:35:35 -0700 (PDT)
Date: Fri, 26 Jul 2024 05:35:37 +0000 (UTC)
From: jsuto <notifications@github.com>
Message-ID: <jsuto/piler/issues/109/2252007730@github.com>
In-Reply-To: <jsuto/piler/issues/109@github.com>
References: <jsuto/piler/issues/109@github.com>
Subject: Re: [jsuto/piler] [BUG] Docker: searchd OOM (Issue #109)
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_66a335a7cc166_761c5c52125b";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Precedence: list
X-GitHub-Sender: jsuto
X-GitHub-Recipient: vmario89
X-GitHub-Reason: subscribed
List-ID: jsuto/piler <piler.jsuto.github.com>
List-Archive: https://github.com/jsuto/piler
List-Post: <mailto:reply+REDACTED@reply.github.com>
List-Unsubscribe: 
 <mailto:unsub+REDACTED@reply.github.com>,
 =?us-ascii?Q?=3Chttps=3A=2F=2Fgithub=2Ecom=2Fnotifications=2Funsubscribe=2Fone-click=REDACTED?=
 =?us-ascii?Q?REDACTED?=
 =?us-ascii?Q?CHTLM=3E?=
List-Unsubscribe-Post: List-Unsubscribe=One-Click
X-Auto-Response-Suppress: All
destinations: user@example.com
X-GitHub-Recipient-Address: user@example.com
Reply-To: jsuto/piler
	<reply+REDACTED@reply.github.com>
X-SG-EID: 
 =?us-ascii?Q?u001=REDACTED+REDACTED?=
 =?us-ascii?Q?REDACTED?=
 =?us-ascii?Q?REDACTED=2FL67DP=REDACTED?=
 =?us-ascii?Q?Xke1CEwfF6SULTh1TNkTzh49tt+L9sSPDVOfFv5?=
 =?us-ascii?Q?vvNw45OYWi+rsee0HnbIyjMLw=2FRb2ZBhXhUgqOp?=
 =?us-ascii?Q?=2FZjPtwwbHUbBA7fe0UpGO8=3D?=
To: jsuto/piler <piler@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
X-Entity-ID: u001.h3RSp2myFsXwI84tgZKC3Q==

```

**Comment by jsuto** [comment]
It works as expected. Cc: address is subscribed@noreply.github.com which can be seen in the pilertest output:


to: *jsuto piler piler@noreply.github.com piler noreply github com subscribed subscribed@noreply.github.com subscribed noreply github com  (noreply.github.com )*

**Comment by vmario89** [comment]
hi,
the screenshot from Thunderbirds lists:
From =  notifications@github.com
To = piler@noreply.github.com
Cc = user@example.com (the masked one in red frame) and author@noreply.github.com

i have a archive rule which says "please do not archive mails which come To/Cc user@example.com"

pilertest does not list user@example.com

For me it beens the To/Cc line is not complete to match the filter then

**Comment by jsuto** [comment]
Can you zip the original eml file and send it to my email address (see ```piler -V``` output)? I'm confused with the obfuscated addresses and to figure out which belongs to which header?
