### ISSUE TITLE
CSS Theme is cluttered in mobile view

### ISSUE THREAD

**Issue by vmario89** [jsuto/piler#120]
The views on mobile device 
- are differently sized (depends on the url we have opened). Compare the 2 screenshots. On one the font is huge, on the other it  is really small
- the menus at top are cut off half

i think to make it compatible to mobile it needs some adjustments in CSS and Javascript

both screenshots are made from the same mobile layout size.
![Screenshot 2024-07-28 at 11-59-06 Nutzungsstatistik](https://github.com/user-attachments/assets/c486c9d7-f807-4bd9-b6ff-0db22e24f177)
![Screenshot 2024-07-28 at 11-58-55 ](https://github.com/user-attachments/assets/0210b05e-9fbd-4e76-8c21-3ce9d2687885)

**Comment by jsuto** [comment]
The layout doesn't support mobile devices at the moment. I can see that you are using the admin user on these screens, however I'd still start with updating the search page to support smaller screens. I'll keep you posted.

**Comment by jsuto** [comment]
For the moment the search and audit pages are fixed to give a better look on mobile devices.
The rest of the admin pages might be improved at a later release.
