### ISSUE TITLE
Mail restore function for auditor does not work

### ISSUE THREAD

**Issue by vmario89** [jsuto/piler#124]
Hi,
when being logged in as auditor, i can select a mail and click restore mail. Then a popup appears to enter the target mail address. Entering the mail address and clicking ok says that it was successfully sent, but the mail never arrives. there is no error log output. 

![Screenshot_20240730_162632](https://github.com/user-attachments/assets/b3266572-0d08-4238-ad54-8dd974a3e097)

when being logged is as the proper imap mailbox user, then the restore works. and the user does not need to enter the target mail address because its prefilled.

i think the behaviour in auditor mode is a bug.

**Comment by jsuto** [comment]
What relevant settings do you have in config-site.php for the email restore? smtp or imap? If imap, then auditor cannot restore by design.

**Comment by vmario89** [comment]
i have a working configured smarthost smtp setting. And i also use the imap settings to allow users to login with their imap credentials. But the auditor is the auditor@local user

```
$config['ENABLE_IMAP_AUTH'] = 1;
$config['RESTORE_OVER_IMAP'] = 1;
$config['STRIP_DOMAIN_NAME_FROM_USERNAME'] = 0;
$config['IMAP_RESTORE_FOLDER_INBOX'] = 'INBOX';
$config['IMAP_RESTORE_FOLDER_SENT'] = 'Sent';
$config['IMAP_HOST'] = 'mail.redacted.de';
$config['IMAP_PORT'] = 143;
$config['IMAP_SSL'] = 'TLS';
$config['SMARTHOST'] = 'mail.redacted.de';
$config['SMARTHOST_PORT'] = 587;
$config['SMARTHOST_USER'] = 'redacted@redacted.de';
$config['SMARTHOST_PASSWORD'] = 'redacted';
$config['SMTP_DOMAIN'] = 'redacted.de';
$config['SMTP_FROMADDR'] = 'no-reply@redacted.redacted.de';
$config['ADMIN_EMAIL'] = 'redacted@redacted.de';
$config['USE_EMAIL_AS_USERNAME'] = 1;
```
