### ISSUE TITLE
[FEATURE] add option to sort rules

### ISSUE THREAD

**Issue by vmario89** [jsuto/piler#125]
In the backend i have now ~30 archive rules. It's hard to read them because the table has no option to sort by a..z / z..a. It would be cool to have some simple javascript arrows to auto-sort by name

https://www.w3schools.com/howto/howto_js_sort_table.asp

**Comment by jsuto** [comment]
By which field's name do you want to sort the archiving rules?

**Comment by vmario89** [comment]
![grafik](https://github.com/user-attachments/assets/8417679a-0f63-4b92-976a-f5c558e4b567)

would be helpful to order by from: or to: or subject alphabetically

**Comment by vmario89** [comment]
thank you very mich @jsuto !
