### ISSUE TITLE
[FEATURE] How to delete more than 20 mails at once?

### ISSUE THREAD

**Issue by vmario89** [jsuto/piler#126]
Hi,

when deleting unneeded mails (like system log mails) i can only select a max. of 20 mails. then i can press delete and search again to select the next 20 entries. this is cumbersome. is there any chance to select more entries at once or some thing to do the same on command line?

**Comment by jsuto** [comment]
You can update the page length to a greater number, eg. 50. Or you may increase it if you add $paging array (see config.php) with greater values to config-site.php.

You may achieve something similar by fixing the metadata table ```retained``` column to the past (eg. yesterday), then run the purge utility. The total mail count supposed change depends on the RT value. Do you use real time or plain index?

**Comment by vmario89** [comment]
thank for that hint!

i adjusted $config['PAGE_LEN'] = 50; in GUI. The sql solution is good!
