### ISSUE TITLE
[FEATURE] Unclear error messages by pilerimport (duplicate id:, helper: execl)

### ISSUE THREAD

**Issue by dilyanpalauzov** [jsuto/piler#133]
I feed the output of `pilerexport` to `pilerimport -r -d <directoryname>`.  It prints:
> duplicate: ./6608154.eml (duplicate id: 4789233)

or logs
> Aug  6 04:07:39 ip-10-65-6-149 pilerimport[32695]: error: helper: execl

It is not clear, what means "duplicate id".  Does it mean that the same message was already imported (unlikely), the message with the same Message-ID was already imported, or an eml message with the same hash value was already imported (also unlikely, but with millions of emails there might be hash collisions).

Execl should be more descriptive in what exactly failed and how to fix it. I have
```
# grep -h HAVE piler-config.h
#define HAVE_DAEMON 1
/* #undef HAVE_PDFTOTEXT */
#define HAVE_CATDOC "/usr/bin/catdoc"
#define HAVE_CATPPT "/usr/bin/catppt"
#define HAVE_XLS2CSV "/usr/bin/xls2csv"
/* #undef HAVE_PPTHTML */
#define HAVE_UNRTF "/usr/bin/unrtf"
#define HAVE_TNEF "/usr/bin/tnef"
#define HAVE_ZIP 1
/* #undef HAVE_TWEAK_SENT_TIME */
/* #undef HAVE_SUPPORT_FOR_COMPAT_STORAGE_LAYOUT */
```

**Comment by dilyanpalauzov** [comment]
From the manticore.log, Buddy makes problems.  Are these essential?  I would say at that time there were no users of the web interface of Piler, only `pilerimport` was working.
```
[Wed Aug  7 05:44:45.327 2024] [780] rt: table piler1: ramchunk saved ok (mode=periodic, last TID=4389002, current TID=4399661, ram=386.120 Mb, time delta=302 sec, took=2.233 sec)
[Wed Aug  7 05:47:45.944 2024] [781] [BUDDY] Fatal error: Uncaught Manticoresearch\Buddy\Core\Error\ManticoreSearchClientError: Error while async request: 104: Connection reset by peer in /usr/share/manticore/modules/manticore-buddy/vendor/manticoresoftware/buddy-core/src/ManticoreSearch/Client.php:175
[Wed Aug  7 05:47:45.944 2024] [781] [BUDDY] Stack trace:
[Wed Aug  7 05:47:45.944 2024] [781] [BUDDY] #0 /usr/share/manticore/modules/manticore-buddy/vendor/manticoresoftware/buddy-core/src/ManticoreSearch/Client.php(142): Manticoresearch\Buddy\Core\ManticoreSearch\Client->runAsyncRequest('sql?mode=raw', 'query=SHOW+VARI...', Array)
[Wed Aug  7 05:47:45.944 2024] [781] [BUDDY] #1 /usr/share/manticore/modules/manticore-buddy/src/Lib/Metric.php(551): Manticoresearch\Buddy\Core\ManticoreSearch\Client->sendRequest('query=SHOW+VARI...')
[Wed Aug  7 05:47:45.944 2024] [781] [BUDDY] #2 /usr/share/manticore/modules/manticore-buddy/src/Lib/Metric.php(488): Manticoresearch\Buddy\Base\Lib\Metric->sendManticoreRequest('SHOW VARIABLES')
[Wed Aug  7 05:47:45.944 2024] [781] [BUDDY] #3 /usr/share/manticore/modules/manticore-buddy/src/Lib/Metric.php(250): Manticoresearch\Buddy\Base\Lib\Metric->getVariableLabels()
[Wed Aug  7 05:47:45.944 2024] [781] [BUDDY] #4 /usr/share/manticore/modules/manticore-buddy/src/Lib/Metric.php(203): Manticoresearch\Buddy\Base\Lib\Metric->snapshot()
[Wed Aug  7 05:47:45.944 2024] [781] [BUDDY] #5 /usr/share/manticore/modules/manticore-buddy/src/Lib/MetricThread.php(103): Manticoresearch\Buddy\Base\Lib\Metric->checkAndSnapshot(300)
[Wed Aug  7 05:47:45.944 2024] [781] [BUDDY] #6 [internal function]: Manticoresearch\Buddy\Base\Lib\MetricThread::Manticoresearch\Buddy\Base\Lib\{closure}(Object(Swoole\Process))
[Wed Aug  7 05:47:45.944 2024] [781] [BUDDY] #7 {main}
[Wed Aug  7 05:47:45.944 2024] [781] [BUDDY]   thrown in /usr/share/manticore/modules/manticore-buddy/vendor/manticoresoftware/buddy-core/src/ManticoreSearch/Client.php on line 175
[Wed Aug  7 05:47:45.987 2024] [780] [BUDDY] [2024-08-07 05:47:45 $827.0]       WARNING Server::check_worker_exit_status(): worker(pid=79945, id=1) abnormal exit, status=255, signal=0
[Wed Aug  7 05:49:48.410 2024] [780] rt: table piler1: ramchunk saved ok (mode=periodic, last TID=4399661, current TID=4410365, ram=486.150 Mb, time delta=303 sec, took=3.083 sec)
```

**Comment by dilyanpalauzov** [comment]
> duplicate: ./6608154.eml (duplicate id: 4789233)

Provided that 6608154 is not imported, why does `pilerimpord -r ` delete it?

**Comment by jsuto** [comment]
A duplicated message means that it's Message-ID can be found in the metadata table. Now the trick is if you have 2+ emails without Message-ID: header, then the 2nd and subsequent emails also will be marked as duplicates. Anyway, each emails should have a unique such header.

The ```error: helper: execl``` indicates an error or warning when running an external helper the extract the textual contents of an attachment. Unfortunately, piler can't do much about it.

And finally, regarding the buddy service, I can live without it. If you want it (check the manticore docs to figure out if it's worth), then please report this issue to the manticore support forum.

Also, keep keep a single topic for a single github issue.

**Comment by dilyanpalauzov** [comment]
What does mean the output of `pilerimport`:
```
failed to import: ./2440249.eml (id: 5000000066b83fb92c2eb8ec00cf6f05a031)
ERROR: error importing: './2440249.eml'
```
When ` error: helper: execl` is logged, Piler should include information which program was called how and why Piler thinks the program failed.  `pilerimport -r` should have an additional option not to delete messages producing `error: helper: execl`.  Otherwise this error message is useless - it is not even clear to which email message the error refers and it does not provide enough information what action to take in order to resolve the error.

**Comment by jsuto** [comment]
It means just what it sounds: 2440249.eml was not archived. I addressed the helper: execl problem in the other issue.
