### ISSUE TITLE
[BUG] Suggest installing ppthtml instead of xlhtml

### ISSUE THREAD

**Issue by dilyanpalauzov** [jsuto/piler#134]
https://www.mailpiler.org/installation/ suggests installing xlhtml and does not say anything about ppthtml.

The source code of piler does not mention xlhtml anywhere, but utilizes ppthtml.

* In https://www.mailpiler.org/installation/ replace xlhtml with ppthtml.

**Comment by jsuto** [comment]
xlhtml contains ppthtml. I'll fix the docs to include a link to the tar.gz file.
