### ISSUE TITLE
[BUG] Discontinue proposing installation of XCache

### ISSUE THREAD

**Issue by dilyanpalauzov** [jsuto/piler#135]
https://www.mailpiler.org/installation/ says PHP 7 and 8 are supported, XCache is optional.

XCache does not work with PHP 7: https://groups.google.com/g/xcache/c/xgEnMwcqpZQ.

**Comment by jsuto** [comment]
Xcache is an optional component. Don't try use it on unsupported releases of PHP.

**Comment by dilyanpalauzov** [comment]
I wanted to say, that in the past I used XCache.  After switching to, I think PHP 7, XCache stopped working.  It is also not working with PHP 8.  My understanding is that XCache cannot be used with PHP 7 or PHP 8, Piler runs only with PHP 7 or PHP 8, and https://www.mailpiler.org/installation/ recommends installing XCache, when using Piler.

**Comment by jsuto** [comment]
Right. It seems that the last release of xcache is quite some times ago. I'll remove it from the docs.
