### ISSUE TITLE
[BUG] path prefix not working 

### ISSUE THREAD

**Issue by th-2021** [jsuto/piler#136]
I did a fresh install of 1.4.6 and followed the RELEASE_NOTES to serve with path prefix.

$config[SITE_NAME_CONST] = 'tom-ml351';
$config['PATH_PREFIX'] = '/mail/';
$config['SITE_URL'] = 'http://' . $config[SITE_NAME_CONST] . '/mail/';

...

        location /mail {
            alias /var/piler/www;
            index  index.php index.html;
            try_files $uri $uri/ /index.php;

            location ~ \.php$ {
              fastcgi_param SCRIPT_FILENAME $request_filename;

              fastcgi_pass unix:/run/php/php8.3-fpm.sock;
              fastcgi_index index.php;
              include fastcgi_params;
            }

            location ~* \.(ico|css|js|gif|jpe?g|png)$ {
               expires 2w;
            }
        }

        rewrite /mail/search.php /mail/index.php?route=search/search&type=simple;
        rewrite /mail/advanced.php /mail/index.php?route=search/search&type=advanced;
...

    base_url: location.origin + '/mail/',

But when I try to login I get:
GET https://tom-ml351/assets/images/archive-logo-lg.png 404 (Not Found)
GET https://tom-ml351/assets/images/archive-logo-lg.png 404 (Not Found)

The path prefix is missing.

What did I miss?

**Comment by th-2021** [comment]
I think I found it. In config.php.in PATH_PREFIX is set to '/' and several paths are set before PATH_PREFIX override from config-site.php is applied. Not sure, what's the best solution to this.
Either move all PATH_PREFIX related lines after config-site.php or change PATH_PREFIX in config.php during start.sh.

**Comment by th-2021** [comment]
Two more occurrences still above config-site.php:

$config['JS_CODE'] = '
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="' . $config['PATH_PREFIX'] . 'assets/js/piler.js"></script>
';

$config['CUSTOM_CSS'] = '';
$config['CSS_CODE'] = '
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.min.css" integrity="sha256-6MNujrdbV0Z7S927PzUMXOmMLwkKdsdD7XIl/w89HMQ=" crossorigin="anonymous">

   <link rel="stylesheet" href="' . $config['PATH_PREFIX'] . 'assets/css/piler.css" />
';

**Comment by jsuto** [comment]
Thanks for noticing, I've just fixed in a commit to master.
