### ISSUE TITLE
[BUG] Why do I have in table `counter` two identical rows, while ModelStatCounter.get_counters expects only one?

### ISSUE THREAD

**Issue by dilyanpalauzov** [jsuto/piler#138]
```
$ git grep TABLE_COUNTER
config.php.in:define('TABLE_COUNTER', 'counter');
config.php.in:define('TABLE_COUNTER_MSG', 'counter_messages');
webui/model/stat/counter.php:      $query = $this->db->query("SELECT * FROM " . TABLE_COUNTER);
```
Likely the definition of TABLE_COUNTER_MSG is not necessary.

I noticed that on a Piler 1.4.6 RT-Manticore system /index.php?route=health/health shows “Archive Size 1kb (1kb)”, despite having inserted via `pilerimport` many emails.  In piler.conf I have update_counters_to_memcached=0 since the beginning, so for the counters it should be irrelevant, whether memcached is configured properly.

I see that the archive size comes from ModelStatCounter.get_counters() { … "SELECT * FROM counter" }.  In manticore I see nowhere table counter, only in mysql:
```
$  mysql --port=9306 -h0
mysql> show tables;
+--------+------+
| Index  | Type |
+--------+------+
| note1  | rt   |
| piler1 | rt   |
| tag1   | rt   |
+--------+------+
3 rows in set (0.00 sec)

$ mysql piler
mysql> select * from counter;
+----------+-------+-----------+--------+--------------+--------------+
| rcvd     | virus | duplicate | ignore | size         | stored_size  |
+----------+-------+-----------+--------+--------------+--------------+
| 10402527 |     0 |       519 |      0 | 533499377395 | 159421679744 |
| 10402527 |     0 |       519 |      0 | 533499377395 | 159421679744 |
+----------+-------+-----------+--------+--------------+--------------+
```

Back to  ModelStatCounter.get_counters() it contains
```
      if($query->num_rows == 1) {
         $asize = $query->row['size'];
         $ssize = $query->row['stored_size'];

         unset($query->row['size']);
         unset($query->row['stored_size']);

         $counter = $query->row;
      }

      return array ($asize, $ssize, $counter);
```

So why do I have in table counter two identical rows?  From where is this row inserted and why aren't the entries there unuque?

The table sph_counter is empty and my reading is that it is anyway only filled in the absence of RT.

**Comment by dilyanpalauzov** [comment]
After the current pilerimport stopped, the table is
```
mysql> select * from counter;                                                                                         
+----------+-------+-----------+--------+--------------+--------------+                                               
| rcvd     | virus | duplicate | ignore | size         | stored_size  |                                               
+----------+-------+-----------+--------+--------------+--------------+                                               
| 11334012 |     0 |       522 |      0 | 564694737935 | 169452437936 |                                               
| 11334012 |     0 |       522 |      0 | 564694737935 | 169452437936 |                                               
+----------+-------+-----------+--------+--------------+--------------+                                               
2 rows in set (0.00 sec)                                                                                              
                                                                                                                      
mysql> delete from counter limit 1;                                                                                   
Query OK, 1 row affected (0.01 sec)

mysql> select * from counter; 
+----------+-------+-----------+--------+--------------+--------------+
| rcvd     | virus | duplicate | ignore | size         | stored_size  |
+----------+-------+-----------+--------+--------------+--------------+
| 11334012 |     0 |       522 |      0 | 564694737935 | 169452437936 |
+----------+-------+-----------+--------+--------------+--------------+
1 row in set (0.00 sec)
```
So both rows were updated to the same value. After deleting one of the rows, the web interface shows archive sizes, different from 1kb.

**Comment by jsuto** [comment]
I've removed the unused definition from config.php.in.

I'm not sure why you have 2 rows in the counter table. Neither the piler binaries, nor the GUI inserts any new rows. The only place where I can find an insert is util/db-mysql.sql

Also, the displayed archive size doesn't depend on the RT settings, because it's read from the counter table. So unfortunately I can't reproduce either of these conditions.

**Comment by dilyanpalauzov** [comment]
Hm, okay, I ran probably the installation procedure twice, as at some moment the system was in bad state.  Then I removed the entries in metadata, rcpt, domain, v_messages, but not from `counters`, and installed again.  I am not sure.  But having UNIQUE there would have prohibited two rows.
