### ISSUE TITLE
[BUG] Do not show “Sphinx main (total) index” on health page, when RT=1

### ISSUE THREAD

**Issue by dilyanpalauzov** [jsuto/piler#139]
util/postinstall.sh.in contains
```bash
load_default_values() {
  RT=1	
}
make_cron_entries() {
      [[ $RT -eq 1 ]] || echo "5,35 * * * * ${LIBEXECDIR}/piler/indexer.delta.sh";
      [[ $RT -eq 1 ]] || echo "30   2 * * * ${LIBEXECDIR}/piler/indexer.main.sh";
      echo "40 3 * * * ${LIBEXECDIR}/piler/purge.sh";
      [[ $RT -eq 1 ]] || echo "*/15 * * * * ${INDEXER} --quiet tag1 --rotate --config ${PILER_CONFIG_DIR}/manticore.conf";
      [[ $RT -eq 1 ]] || echo "*/15 * * * * ${INDEXER} --quiet note1 --rotate --config ${PILER_CONFIG_DIR}/manticore.conf";
}
```

That is, when RT is enabled, the default, there is no need to run indexer.delta.sh and indexer.main.sh .  However it is indexer.main.sh, which creates piler/stat/total_index_size and piler/stat/current_main_index_size .  When the index_size files are missing, index.php?route=health/health shows “Sphinx main (total) index 1k (1k)”.  My understanding is that under RT there is no “Sphinx main (total) index”, and therefore this should not be rendered on the web page.

**Comment by jsuto** [comment]
I've addressed this in #140

**Comment by dilyanpalauzov** [comment]
I do not see how is this relevant to https://github.com/jsuto/piler/issues/140 and permissions on the file system.

When real-time is enabled, piler/indexer.main.sh is not run (from crontab). When indexer.main.sh is not run, it does not create  piler/stat/total_index_size and piler/stat/current_main_index_size.  Then the web interface should not show the values for these index sizes (under Sphinx main (total) index).

In addition, indexer.main.sh could be executed from util/reindex.sh, which I do not calls, as for I do not what reindex.sh is good for.

**Comment by jsuto** [comment]
My bad, I confused it with the other. Anyway, the fix is on its way. It will query sphinx/manticore for the index size, so it hall work with both RT and plain index settings.
