### ISSUE TITLE
[BUG] Dead link in etc/sphinx.conf.in

### ISSUE THREAD

**Issue by dilyanpalauzov** [jsuto/piler#144]
> / In order to comply with it you must enable SPHINX_STRICT_SCHEMA variable
> // Be sure to check out http://www.mailpiler.org/wiki/current:sphinx3 for more
> // NB: The SPHINX_STRICT_SCHEMA in sphinx.conf MUST BE THE SAME as in config.php (or in config-site.php)
> //
> define('SPHINX_STRICT_SCHEMA', 1);

http://www.mailpiler.org/wiki/current:sphinx3  does not exist.

**Comment by jsuto** [comment]
Fixed.

**Comment by dilyanpalauzov** [comment]
Is my reading correct, that manticore does not have the notion of STRICT_SCHEMA, as opposed to sphinx?

**Comment by jsuto** [comment]
Correct.
