### ISSUE TITLE
[BUG] path prefix : search-helper.php not found

### ISSUE THREAD

**Issue by th-2021** [jsuto/piler#147]
POST https://tom-ml351/search-helper.php 404 (Not Found)

Prefix is missing.

nginx is correct:
 rewrite /mail/search-helper.php /mail/index.php?route=search/helper;

**Comment by jsuto** [comment]
Can you try the following fix?

```
--- a/webui/system/misc.php
+++ b/webui/system/misc.php
@@ -393,7 +393,7 @@ function escape_gt_lt_quote_symbols($s = '') {
 
 function get_search_url_by_page($page = 0) {
 
-   return "/search-helper.php?page=$page";
+   return PATH_PREFIX . 'search-helper.php?page=' . (int)$page;
 
```

**Comment by th-2021** [comment]
No change. Prefix still missing

**Comment by jsuto** [comment]
Assuming the base_url is set in assets/js/piler.js, this is the only other place that references search-helper.php

**Comment by th-2021** [comment]
My base_url change was lost, when I started the new image. It's working now.

How can I set the base_url? piler.js is part of the image. A patch by start,sh? Or is there an easier solution?

**Comment by jsuto** [comment]
An easier solution doesn't come to my mind, please apply your change again.

**Comment by th-2021** [comment]
# Fix for PATH_PREFIX
   PATH_PREFIX=`grep PATH_PREFIX /etc/piler/config-site.php | awk '{ print $3 }' | tr ";" ","`
   sed -i -e "s#location.origin\ +\ .*#location.origin\ +\ $PATH_PREFIX#" /var/piler/www/assets/js/piler.js

To me the result looks ok, but firefox throws an error:
Uncaught SyntaxError: missing } after property list[piler.js:8:43](https://tom-ml351/mail/assets/js/piler.js)note: { opened at line 2, column 1

Chrome works.

**Comment by th-2021** [comment]
firefox error was a cache issue. firefox works as well
