### ISSUE TITLE
[BUG] When no SMTP STARTTLS is going to be announced, piler shall not fail, if it cannot load the pemfile

### ISSUE THREAD

**Issue by dilyanpalauzov** [jsuto/piler#151]
My understanding is that the PEM file is only needed, when `enable_tls=1`.  Currently, when `enable_tls=0` and pemfile is missing, piler logs
```
Aug 12 09:33:24 2d370abbbedf piler[1883]: reloaded config: /usr/local/etc/piler/piler.conf
Aug 12 09:33:24 2d370abbbedf piler[1883]: cannot read keyfile: /usr/local/etc/piler/piler.key
Aug 12 09:33:24 2d370abbbedf piler[1883]: ERR: reading cipher key
```
* When no TLS is going to happen, Piler should skip loading its PEM file.

**Comment by jsuto** [comment]
The pemfile is required when you have enable_tls=1. However, the mentioned syslog entries have nothing to do with PEM or STARTTLS. Notice that it's not the piler-smtp daemon, instead piler daemon.

**Comment by dilyanpalauzov** [comment]
Yes, but for the case where enable_tls=0, I do not understand why the PEM file is required by the piler daemon.

**Comment by jsuto** [comment]
Where can you see that the piler daemon requires the pem file?

**Comment by dilyanpalauzov** [comment]
In the logs above. I tried setting `enable_tls=0`, removed the PEM file, and then piler does not start. I hope I have not done the tests in a wrong way.

**Comment by jsuto** [comment]
I told you already: those logs have nothing to do with the pem file.

**Comment by dilyanpalauzov** [comment]
The above error messages are emitted by the piler project.  My understanding is that they are related to the setting `pemfile=`, when `enable_tls=0`. In any case, what I am saying, under certain conditions, like `enable_tls=0` and probably others, Piler does not need pem file/key cipher file.  Under these conditions, it should not print error messages, that it cannot load read the keyfile, and abort.

**Comment by jsuto** [comment]
I'm telling you the 3rd time: your understanding is incorrect. The keyfile is not the same as the pem file. Please spare me from the need to repeat myself the 4th time, instead check the ownership and permissions on the piler.key file and make sure user or group piler can read it.

**Comment by dilyanpalauzov** [comment]
Okay.  How should piler be configured, so that it does not require keyfile?
