### ISSUE TITLE
Installing the piler 1.4.6

### ISSUE THREAD

**Issue by munagala05** [jsuto/piler#155]
Dear Sir,

I am trying to install piler 1.4.6 in ubuntu 24.04 it is not installing please help me with any document.

Thanks in advance.

**Comment by jsuto** [comment]
Please provide context, details, any meaningful information. You are expected to fill the template when opening an issue.

**Comment by munagala05** [comment]
Dear Sir,
I am getting this error 

 /etc/init.d/rc.searchd start
starting searchd . . .
Sphinx 3.7.1 (commit da9f8a4e7)
Copyright (c) 2001-2024, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file '/usr/local/etc/piler/manticore.conf'...
WARNING: key 'rt_field' is deprecated in /usr/local/etc/piler/manticore.conf line 23; use 'field' instead.
WARNING: key 'rt_field' is deprecated in /usr/local/etc/piler/manticore.conf line 24; use 'field' instead.
WARNING: key 'rt_field' is deprecated in /usr/local/etc/piler/manticore.conf line 25; use 'field' instead.
WARNING: key 'rt_field' is deprecated in /usr/local/etc/piler/manticore.conf line 26; use 'field' instead.
WARNING: key 'rt_field' is deprecated in /usr/local/etc/piler/manticore.conf line 27; use 'field' instead.
WARNING: 21 more warnings skipped.
ERROR: unknown key name 'network_timeout' in /usr/local/etc/piler/manticore.conf line 107 col 24.
WARNING: 21 more warnings skipped.
ERROR: unknown key name 'network_timeout' in /usr/local/etc/piler/manticore.conf line 107 col 1.
FATAL: failed to parse config file '/usr/local/etc/piler/manticore.conf'
shutdown complete

**Comment by munagala05** [comment]
Dear Sir,
Please do needfull.

**Comment by jsuto** [comment]
You have sphinx installed for some reason, but you want to use the manticore.conf file. Of course, it won't work. Either use sphinx with sphinx.conf or manticore with manticore.conf
