### ISSUE TITLE
[BUG] <make: *** [Makefile:129: postinstall] Error 1>

### ISSUE THREAD

**Issue by ewebsk** [jsuto/piler#158]
**Describe the bug**
after run make postinstall on debian 12 I get only make: *** [Makefile:129: postinstall] Error 1

**To Reproduce**
just run make postinstall

**Expected behavior**
run post installation configuration

**Screenshots**
not needed

**Piler version:**
1.4.6

**Additional context**

**Notes**

**Comment by jsuto** [comment]
Is that all the output you get? In that case you must have missed something. When I type make postinstall, then it starts the (pos)installer just fine.

```
This is the postinstall utility for piler
It should be run only at the first install. DO NOT run on an existing piler installation!


Continue? [Y/N] [N] 
```
