### ISSUE TITLE
[FEATURE] show logs on /dev/stdout

### ISSUE THREAD

**Issue by th-2021** [jsuto/piler#161]
In kubernetes logs are shown with kubectl logs ... (simple logging). The logs with piler are in /var/log and not shown this way.
One solution would be to send important messages to /dev/stdout (in rsyslog config).

**Comment by jsuto** [comment]
It can be done by fixing the rsyslog config, however you may be better off using a dedicated log shipping app like fluentbit to deliver logs to ELK, Grafana cloud, etc. I use grafana cloud's free tier to display various metrics, dashboards and logs.

**Comment by jsuto** [comment]
It's possible, however, I still believe that all logs should be at a single place.
