### ISSUE TITLE
piler and piler-smtp fail to properly run since antivirus option was removed from cfg.h and cfg.c

### ISSUE THREAD

**Issue by vmario89** [jsuto/piler#164]
Hi,
since commit https://github.com/jsuto/piler/commit/8cf96dce08e6eee6157142804a7879a3aece9eb9 i can compile piler, but it will fail to start when running piler.service and piler-smtp.service.

it warns with "ERR: chdir() to working directory failed"

as soon as i add back those two lines, i can compile and properly run

i am doing the following procedure:

```
cd /opt/piler
git stash
git pull
git clean -xdf #remove older files from compilation
git checkout master
./configure --prefix=/ --localstatedir=/var --enable-memcached
make
make install
ldconfig
```

**Comment by vmario89** [comment]
might belong to https://github.com/jsuto/piler/issues/127

**Comment by vmario89** [comment]
i know that the chdir() belongs to the workdir and it says it cannot change to that dir. the fun fact is, that as i mentioned, it works when adding the 2 removed lines again. i have no explanation for this right now and it is really strange. it feels like there must be some unknown side effect in the build routine ...

btw. pyler seems to rely on those static prefixes and paths and it ignores the setting "WorkingDirectory" in systemd service file, which sets the environment for the process normally, if defined. i used `ExecStartPre=/bin/pwd -P` to validate, the the service correctly applies the WorkingDirectory, but piler ignores it.

**Comment by vmario89** [comment]
same fact for piler-smtp: as soon as i remove those lines about antivirus from cfg.c and cfg.h and compile it, piler-smtp will not recreate /tmp/ and /tmp/{0,1,2,} folders by itself, as it does before that change

**Comment by vmario89** [comment]
i also tried to find a difference between
`./configure --prefix=/ --localstatedir=/var --enable-memcached`
and 
`./configure --prefix=/ --localstatedir=/var --enable-memcached --enable-clamd`
but this makes no difference about the errors i get

compared to the recent master and the commit https://github.com/jsuto/piler/commit/8cf96dce08e6eee6157142804a7879a3aece9eb9

**Comment by jsuto** [comment]
Using --prefix=/ is a bit odd to me, though you are free to customize it the way you want. However, piler should definitely NOT work in /tmp. Also piler uses the directories specified in piler.conf, and not the WorkingDirectory settings in the systemd files.

Try the following: run pilerconf to print the directories that piler wants to use. Make sure that they exist and writable by piler user, then run ```piler``` from the command line. Let me know if it can start properly.

**Comment by jsuto** [comment]
No further update.
