### ISSUE TITLE
[BUG?] PDF-Print/-Export (Icon) result in incomplete original email

### ISSUE THREAD

**Issue by Winteriver** [jsuto/piler#177]
**Describe the bug**
PDF-Print/-Export should include all details of the original email. Like a print in an email client (e.g. Thunderbird, Outlook). 
Right now lines of "Subject", "From", "To", "Date" and also the included "Caution:" lines are missing.
Only email body will be printed/PDF-exported, which is not enough to send out this email as a proof of receiving/sending.

**To Reproduce**
1. Go to https://demo.mailpiler.com/login
2. Login as "auditor@local"
3. Choose any email (I have chosen this email:
Subject: Re:Reusable Bags Manufacturer
From: "ACMEY Co." <lanxifa26@163.com>
To: "info" <info@demo.mailpiler.com>
Date: Wed, 3 May 2023 20:38:10 +0800
4. Click "PDF"
5. See error

**Expected behavior**
PDF-Print/-Export should include all details of the original email. Like a print in an email client (e.g. Thunderbird, Outlook). 
This includes all message parts: "Subject", "From", "To", "Date" and also the included "Caution:" lines.

**Screenshots**
2 Screenshots and the resulting PDF are attached.

**Piler version:**
See the actual demo of 03/09/2024. Version is not shown on login screen or in about section.

Thank you for this great software!
Exporting a complete PDF of an email would really help.
Optionally exporting a PDF with header information would be very helpful as well.

Many thanks, Markus

![20240903 Screenshot 001](https://github.com/user-attachments/assets/c5df9661-e903-4f4b-a6e1-0cb5d7a18167)

![20240903 Screenshot 002](https://github.com/user-attachments/assets/d6bf94b0-c740-41b8-a2a9-03abb069349d)

[50000000645255d413a4c1540084b8f1391a.pdf](https://github.com/user-attachments/files/16850884/50000000645255d413a4c1540084b8f1391a.pdf)

**Comment by jsuto** [comment]
I'll address the issue in the enterprise edition that the demo site runs. Can you reproduce this error in the open source edition as well?

**Comment by Winteriver** [comment]
Many thanks!
Will the PR be included in the open source edition, which we plan to test?

Thanks, Markus

**Comment by jsuto** [comment]
It's already merged to the master branch.
