### ISSUE TITLE
Mobile login restore emails to mailbox missing piler 1.4.6

### ISSUE THREAD

**Issue by ckruijntjens** [jsuto/piler#180]
Hi All,

When i was using the previous version of mailpiler i could login with my mobile device and restore emails to my mailbox. Now the option is only available wen i login on a laptop.

On my mobile device the "Bulk Restore Selected" is not there.

Is this on purpose or am i missing some configuration?

**Comment by jsuto** [comment]
You are correct, both the bulk restore and the restore button have gone to save some space. Also, now that I see it from my mobile, the left side checkboxes can be removed as well from the mobile view.

However, it's easier to put back the "Restore to mailbox" button when you click on the given message that you want to restore, if you really need this feature.

**Comment by jsuto** [comment]
You can. Feel free to apply the templates/message/view.tpl changes from the linked PR.
