### ISSUE TITLE
after mailpiler upgrade error 500 when 2fa should be asked

### ISSUE THREAD

**Issue by ckruijntjens** [jsuto/piler#185]
Hi,

After a git pull and upgrade of mailpiler i can login with my account but it errors out (error 500) when it should be asking for the 2fa code.

I looked in the webserver log and i found this:

2024/09/27 12:54:14 [error] 158#158: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/piler/www/system/misc.php:613
Stack trace:
#0 /var/piler/www/model/user/user.php(77): get_q_string()
#1 /var/piler/www/model/user/auth.php(412): ModelUserUser->get_email_addresses_from_groups()
#2 /var/piler/www/model/user/auth.php(67): ModelUserAuth->checkLoginAgainstIMAP()
#3 /var/piler/www/controller/login/login.php(48): ModelUserAuth->checkLogin()
#4 /var/piler/www/system/front.php(36): ControllerLoginLogin->index()
#5 /var/piler/www/system/front.php(14): Front->execute()
#6 /var/piler/www/index.php(113): Front->dispatch()
#7 {main}
  thrown in /var/piler/www/system/misc.php on line 613" while reading response header from upstream, client: 192.168.2.6, server: piler.ckruijntjens.local, request: "POST /login.php HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "192.168.2.253", referrer: "https://piler.ckruijntjens.nl/"

**Comment by jsuto** [comment]
I couldn't reproduce this issuse using the latest master's HEAD. https://github.com/jsuto/piler/blob/master/webui/model/user/auth.php#L388 ensures that get_q_string() gets an array.

**Comment by ckruijntjens** [comment]
> I couldn't reproduce this issuse using the latest master's HEAD. https://github.com/jsuto/piler/blob/master/webui/model/user/auth.php#L388 ensures that get_q_string() gets an array.

Strange thing. I tried to upgrade again and after this it lets me login with my username and password. Now the 2fa should come up but instead it gives me an error 500?

Could it have to do something with the 2fa plugin?

**Comment by jsuto** [comment]
I think the upgrade might have caused the problem. How about a clean install?

**Comment by ckruijntjens** [comment]
> I think the upgrade might have caused the problem. How about a clean install?

Can i disable 2fa on the command line? maybe if i disable and reenable it will work again?

**Comment by jsuto** [comment]
You can update it in the user_settings in the mysql piler database. Eg.

update user_settings set ga_enabled=1 where user=....

OR

you may turn it off in config-site.php by setting 0 for ENABLE_GOOGLE_AUTHENTICATOR

**Comment by ckruijntjens** [comment]
> You can update it in the user_settings in the mysql piler database. Eg.
> 
> update user_settings set ga_enabled=1 where user=....
> 
> OR
> 
> you may turn it off in config-site.php by setting 0 for ENABLE_GOOGLE_AUTHENTICATOR

Thanks,

Thats not the issue. even when i disable 2fa it gives me error 500 after login.

**Comment by jsuto** [comment]
Then there must be some other issue. As I suggested before: do a clean install, and check if it works for you.

**Comment by ckruijntjens** [comment]
> Then there must be some other issue. As I suggested before: do a clean install, and check if it works for you.

ok will do that. can i easily migrate my excisitng email?

**Comment by ckruijntjens** [comment]
hmm i cant login as admin or auditor either in my old mailpiler installation.

i will reinstall mailpiler today. Can i yust do an rsync on my store (mail) and mailpiler import to get all my old mails back?

**Comment by jsuto** [comment]
Don't reinstall it just yet. Instead created a new, empty, clean installation to verify that the 2FA stuff works properly.

**Comment by ckruijntjens** [comment]
> Don't reinstall it just yet. Instead created a new, empty, clean installation to verify that the 2FA stuff works properly.

Before i do all this. What could it be. In my install before the upgrade i can login with all my mailcow emal adresses.

However i can not login as admin@local or auditor@local.  This also gives me a error 500

**Comment by jsuto** [comment]
Well, it's quite possible.

**Comment by patschi** [comment]
I did indeed find a issue where no array was passed along where expected. I fixed  reported issue https://github.com/patschi/mailpiler-mailcow-integration/issues/4 with https://github.com/patschi/mailpiler-mailcow-integration/commit/644c9135d987a34eb4d1404ca7b0bac2ba11daf7. Google 2FA - with first tests - do also work for me.
