### ISSUE TITLE
[BUG] <try to store same message twice>

### ISSUE THREAD

**Issue by ewebsk** [jsuto/piler#187]
**Describe the bug**
there are duplicates records seen in log file as piler try to store one message twice, some messages are stored at first but some are trying to store twice

**To Reproduce**
no special steps needed just to watch mail.log

**Expected behavior**
store the message at first

**Screenshots**
![Snímka obrazovky 2024-10-10 o 8 02 08](https://github.com/user-attachments/assets/18d21bfe-3fba-4263-82b8-62e86ad19dd2)

**Piler version:**
1.4.6

**Additional context**
Oct 10 07:57:25 piler piler-smtp[4453]: connected from 1xx.1xx.5x.1xx:47822 on fd=6 (active connections: 1)
Oct 10 07:57:25 piler piler-smtp[4453]: DEBUG: total smtp memory allocated: 0, expected total size: 0
Oct 10 07:57:25 piler piler-smtp[4453]: got on fd=6: *EHLO mail.server.com#015#012*
Oct 10 07:57:25 piler piler-smtp[4453]: sent on fd=6: 250-piler.server.com#015#012250-SIZE 50000000#015#012250-STARTTLS#015#012250 8BITMIME#015
Oct 10 07:57:25 piler piler-smtp[4453]: got on fd=6: *STARTTLS#015#012*
Oct 10 07:57:25 piler piler-smtp[4453]: starttls request from client
Oct 10 07:57:25 piler piler-smtp[4453]: sent on fd=6: 220 Ready to start TLS#015
Oct 10 07:57:25 piler piler-smtp[4453]: waiting for ssl handshake
Oct 10 07:57:25 piler piler-smtp[4453]: SSL_accept() result, rc=-1, errorcode: 2, error text: error:00000000:lib(0)::reason(0)
Oct 10 07:57:25 piler piler-smtp[4453]: got on fd=6: *EHLO mail.server.com#015#012*
Oct 10 07:57:25 piler piler-smtp[4453]: sent on fd=6: 250-piler.server.com#015#012250-SIZE 50000000#015#012250 8BITMIME#015
Oct 10 07:57:25 piler piler-smtp[4453]: got on fd=6: *MAIL FROM:<zr.1120@message.com> SIZE=46553#015#012*
Oct 10 07:57:25 piler piler-smtp[4453]: sent on fd=6: 250 Ok#015
Oct 10 07:57:25 piler piler-smtp[4453]: got on fd=6: *RCPT TO:<archive@piler.server.com>#015#012*
Oct 10 07:57:25 piler piler-smtp[4453]: sent on fd=6: 250 Ok#015
Oct 10 07:57:25 piler piler-smtp[4453]: got on fd=6: *DATA#015#012*
Oct 10 07:57:25 piler piler-smtp[4453]: sent on fd=6: 354 Send mail data; end it with <CRLF>.<CRLF>#015
Oct 10 07:57:25 piler piler-smtp[4453]: received: RT92N7ZS999P9B1S, from=zr.1120@message.com, size=47916, client=1xx.1xx.5x.1xx, fd=6, fsync=2533
Oct 10 07:57:25 piler piler-smtp[4453]: sent on fd=6: 250 OK <RT92N7ZS999P9B1S>#015
Oct 10 07:57:25 piler piler-smtp[4453]: got on fd=6: *QUIT#015#012*
Oct 10 07:57:25 piler piler-smtp[4453]: sent on fd=6: 221 piler.server.com Goodbye#015
Oct 10 07:57:25 piler piler-smtp[4453]: disconnected from 1xx.1xx.5x.1xx on fd=6, slot=0, reason=done (0 active connections)
Oct 10 07:57:26 piler piler[4457]: 5000000067076cd0343dec9c00ec09c53ca5: attachment list: i:1, name=*image001.png*, type: *image/png*, size: 9728, int.name: 5000000067076cd0343dec9c00ec09c53ca5.a1, digest: ccc9f35eaced88fa08135e2c5c6ec3c05f70da2bc3abd749ea4fc75f4a4c7adb, dumped: 0
Oct 10 07:57:26 piler piler[4457]: 5000000067076cd0343dec9c00ec09c53ca5: attachment list: i:2, name=*image002.png*, type: *image/png*, size: 2590, int.name: 5000000067076cd0343dec9c00ec09c53ca5.a2, digest: 1ecdeed6785f13c33d738d1b1a7ef02653aa47d67bc1b24222411c79ec5dfc00, dumped: 0
Oct 10 07:57:26 piler piler[4457]: 5000000067076cd0343dec9c00ec09c53ca5: hdr_len: 17088, offset: 3
Oct 10 07:57:26 piler piler[4457]: 5000000067076cd0343dec9c00ec09c53ca5: touch f226503000cfe5a2e7237582d031ef2e825c150a4f6b86f478b2ae4806385dec OK (<AM9P193MB13795F1A18DC988A7DF2613EFC782@AM9P193MB1379.EURP193.PROD.OUTLOOK.COM>)
Oct 10 07:57:26 piler piler[4457]: 5000000067076cd0343dec9c00ec09c53ca5: stored '5000000067076cd0343dec9c00ec09c53ca5.a1' 9728/7410 bytes
Oct 10 07:57:26 piler piler[4457]: 5000000067076cd0343dec9c00ec09c53ca5: stored '5000000067076cd0343dec9c00ec09c53ca5.a2' 2590/2001 bytes
Oct 10 07:57:26 piler piler[451]: 5000000067076cd034eeaab400cd4410dbe8: touch f226503000cfe5a2e7237582d031ef2e825c150a4f6b86f478b2ae4806385dec FAILED (<AM9P193MB13795F1A18DC988A7DF2613EFC782@AM9P193MB1379.EURP193.PROD.OUTLOOK.COM>), error: File exists
Oct 10 07:57:26 piler piler[451]: 1/RT92N7ZS999P9B1S: discarding: duplicate message, id: 0, message-id: <AM9P193MB13795F1A18DC988A7DF2613EFC782@AM9P193MB1379.EURP193.PROD.OUTLOOK.COM>
Oct 10 07:57:26 piler piler[451]: 1/RT92N7ZS999P9B1S: 5000000067076cd034eeaab400cd4410dbe8, size=47916/0, attachments=2, reference=<BY5PR02MB704260DC7F8315C2CAA850F0CA4E9@BY5PR02MB7042.namprd02.prod.outlook.com>, message-id=<AM9P193MB13795F1A18DC988A7DF2613EFC782@AM9P193MB1379.EURP193.PROD.OUTLOOK.COM>, retention=0, folder=0, delay=0.0042, status=duplicate
Oct 10 07:57:26 piler piler[4457]: 5000000067076cd0343dec9c00ec09c53ca5: stored '5000000067076cd0343dec9c00ec09c53ca5.m' 35734/10432 bytes
Oct 10 07:57:26 piler piler[4457]: 5000000067076cd0343dec9c00ec09c53ca5: updated meta reference for '<BY5PR02MB704260DC7F8315C2CAA850F0CA4E9@BY5PR02MB7042.namprd02.prod.outlook.com>', rc=0
Oct 10 07:57:26 piler piler[4457]: 5000000067076cd0343dec9c00ec09c53ca5: stored 1 recipients, rc=0
Oct 10 07:57:26 piler piler[4457]: 5000000067076cd0343dec9c00ec09c53ca5: stored metadata, rc=0
Oct 10 07:57:26 piler piler[4457]: 1/RT92N7ZS999P9B1S: 5000000067076cd0343dec9c00ec09c53ca5, size=47916/19843, attachments=2, reference=<BY5PR02MB704260DC7F8315C2CAA850F0CA4E9@BY5PR02MB7042.namprd02.prod.outlook.com>, message-id=<AM9P193MB13795F1A18DC988A7DF2613EFC782@AM9P193MB1379.EURP193.PROD.OUTLOOK.COM>, retention=3650, folder=0, delay=0.0228, status=stored

**Notes**
If sensitive data is required to understand the situation, then don't copy it to the issue, rather send it to my address (see piler -V output)

**Comment by ewebsk** [comment]
one more log

![Snímka obrazovky 2024-10-10 o 11 23 38](https://github.com/user-attachments/assets/680f3dd9-4ef9-4e3e-914a-f0e021df2806)

**Comment by jsuto** [comment]
I don't understand the "trying to store twice" problem. Piler stores a single copy of each email. If you send the same (with the same Message-ID) email again to piler, then it discards it, and syslogs store=duplicate. That's normal behaviour.

**Comment by ewebsk** [comment]
message from mail server is sent only once but piler try to store it twice and second one failed take a look to last screenshot

**Comment by ewebsk** [comment]
when I do not use adding X-Envelope-To header as written here https://www.mailpiler.org/installation/ on mailserver then this duplicity disappear from logs

**Comment by jsuto** [comment]
I don't understand how adding an extra header to the email on the mail server results in sending 2 copies of the same email to the archive. Anyway, if it solves your problem, I can live with it.

**Comment by ewebsk** [comment]
that was false positive problem is still the same :)

**Comment by jsuto** [comment]
OK. I suspect that if an email has 2+ recipients, then it sends 2+ copies to the archive, 1 for each recpient. You need to find out, if it's really the case, and if you want to do something about it. Anyway, piler works as expected.

**Comment by ewebsk** [comment]
I think problem was empty archive_address= in piler.conf when entered that duplicates from log are gone, now I have problem that some messages are with Message Failed Verification, are some tips to solve this ugly bitch?

**Comment by jsuto** [comment]
No, the archive_address has other purpose. Get the piler id from the mysql piler database, metadata table. Run a query like ```select piler_id from metadata where id=339;```. You'll get a piler id, then run ```pilerget <piler id>``` to retrieve the message. And finally look for errors in the mail log.

**Comment by ewebsk** [comment]
hi some news today I changed vps and problems are gone so I guess that piler is ok but cheap vps from Ethernet Servers was shitty so pls close this report as solved
