### ISSUE TITLE
Moving From old server to new one (Sphinx to Manticore)

### ISSUE THREAD

**Issue by swartjie** [jsuto/piler#192]
Hey Guys,

I am following the guide: https://www.mailpiler.org/migrating-piler-to-a-new-node/
But the one step says "Copy the sphinx files (/var/piler/sphinx/*) from OLD to NEW"

My question though is, The old server uses sphinx, and the newer server is running manticore...
Will the process stay the same or is there a different step that I need to take?

**Comment by jsuto** [comment]
The sphinx db and manticore db are not compatible. In this case don't copy the sphinx data files, rather reindex all emails as the last step.
