### ISSUE TITLE
Web frontend does not render and site not working

### ISSUE THREAD

**Issue by nzkiwiflyer** [jsuto/piler#198]
Greetings
I'm running/testing the latest docker version 1.4.6.
My main lab environment does not have internet access.
The identical setup with internet access works fine.
The stand alone environment without internet does not work.
It looks like something within piler relies on internet access to work.
Is there a list of what this is? Can it be downloaded and work in an offline mode?
Cheers

**Comment by jsuto** [comment]
Check the JS_CODE and CSS_CODE in /var/piler/www/config.php. Download these files, then edit /etc/piler/config-site.php, and put these variables with the fixed values pointing to the local files.
