### ISSUE TITLE
[BUG] Date field in the GUI

### ISSUE THREAD

**Issue by lupin3rd** [jsuto/piler#199]
I try to show the time in the date field of the GUI.
The GUI seem to show the time of Indexer job that import the email.

In my case i import in the same day all  emails by pilerimport and then all emails have the same time.

Piler version: 1.4.6

**Comment by jsuto** [comment]
I don't think it is the case. Please show me the full headers of the email.

**Comment by lupin3rd** [comment]
I attach screenshots.
![2024-11-05_08-51](https://github.com/user-attachments/assets/34cf5672-247e-4770-b5bd-3017011c4a7e)
![2024-11-05_08-49](https://github.com/user-attachments/assets/aa46abdd-9257-4d11-9291-d66b4dc6ba51)
As you can see in the email list, they all have the same indexing times.

**Comment by jsuto** [comment]
Your date template is incorrect. You have the month (m) twice.

**Comment by lupin3rd** [comment]
Sorry @jsuto ! My big mistake :smile:
