### ISSUE TITLE
[BUG] Indexed data not available via GUI after docker compose down && docker compose up -d

### ISSUE THREAD

**Issue by sdsys-ch** [jsuto/piler#207]
Hi @jsuto , great software, thank you!

**Describe the bug**
Current docker image 1.4.6 "looses" indexed emails upon `docker compose down && docker compose up -d`?

**To Reproduce**
1. Grab `docker-compose.yml`, `piler.cnf`, `manticore.conf` from repo or clone locally.
2. Run `docker compose up -d`
3. Use `telnet` or `netcat` to submit test message on port 25
4. Log in as auditor and verify message can be found in the search
5. `docker compose down && docker compose up -d`
6. Log back in: message is "gone"

**Expected behavior**
Message should still be available after service restart. Volumes are persistent etc.

**Piler version:**
 ```
 root@fe9095c700e2:/# piler -V
piler 1.4.6-80dadac, Janos SUTO <snip>

Build Date: Sun Jul 21 04:49:24 UTC 2024
ldd version: ldd (Ubuntu GLIBC 2.39-0ubuntu8.1) 2.39
gcc version: gcc version 13.2.0 (Ubuntu 13.2.0-23ubuntu4)
OS: Linux 089c1dd7121d 6.8.0-1005-oracle #5-Ubuntu SMP Sat Apr 20 04:24:04 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
Configure command: ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-database=mariadb
MySQL client library version: 3.3.10
Extractors: /usr/bin/pdftotext /usr/bin/catdoc /usr/bin/catppt /usr/bin/xls2csv /usr/bin/unrtf /usr/bin/tnef libzip
```

running on `Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:25 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6030 arm64` under orbstack 1.8.2, also tested on `5.15.0-126-generic #136-Ubuntu SMP Wed Nov 6 10:38:22 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux` under docker version 27.3.1.

**Additional context**
While setting `MANTICORE_HOSTNAME=manticore`, piler seems to still be running its own instance:
`docker compose exec piler ps aux`:
```
piler         81  0.0  0.0  54156  3284 ?        S    15:15   0:00 searchd --config /etc/piler/manticore.conf
piler         82  0.1  0.0 990172 16544 ?        Sl   15:15   0:02 searchd --config /etc/piler/manticore.conf
```
but that might be wanted and not related?

I'm new to piler, so maybe this isn't a bug at all and my understanding is lacking despite reading diverse documentation.

**Comment by sdsys-ch** [comment]
@jsuto 
Thanks for the quick reply. Hadn't thought of that, my bad. Will close this.
Any idea on the time frame for the next release?
Thank you for Piler!

**Comment by jsuto** [comment]
Give me a week or two.

**Comment by sdsys-ch** [comment]
> Give me a week or two.

Oh, no hurry. Just wondering if waiting before deploy made sense, preferring separation of concerns w/ docker. Thanks
