### ISSUE TITLE
[FEATURE] [QUESTION] GUI Import Job schedule definition

### ISSUE THREAD

**Issue by rabsym** [jsuto/piler#216]
Hello all,

Sorry if not the proper place to ask/explain this.

Have read that "By default the GUI import job runs 3 times every hour" and would like to ask if this could be changed even from command line, cron or something so. Have individual defined jobs it's own cron?

I need some users to configure and maintain imap archive jobs to download and delete source data executing this kind of task only weekend when no users working.

Thanks in advance.
Raimon

**Comment by jsuto** [comment]
This topic may go to the discussions section. Anyway, it's defined in piler's crontab. The whole import runs based on this setting, the individual jobs have no dedicated timing.

Btw. if possible, I recommend smtp delivery, it's a far more reliable method to get those emails.
