### ISSUE TITLE
[BUG] IMAP import stopped working after 1.4.7 update

### ISSUE THREAD

**Issue by rabsym** [jsuto/piler#217]
Hello,

After updating piler to 1.4.7 version, IMAP import stopped working. Thinking being my fault I did a clean install and getting the same issue.

Don't sure if anything related to new imap behaviour using curl.

I get strange characters when executing pilerimport as seen in the following capture.:

![image](https://github.com/user-attachments/assets/193e41de-d809-469b-af2b-adc5fc30a04d)

Get the same output even using a bad credentials instead of auth failed.

Thanks
Raimon

**Comment by jsuto** [comment]
Try using ```-i imaps://mail.example.com -u ... -p ...``` This automatically selects port 993

Btw. what kind of imap server do you have?

**Comment by rabsym** [comment]
IMAP Server is dovecot.

Regarding your suggestion it did the trick, reading about curl it defaults to "http" when no protocol specified or not identified in hostname.


  /*
   * Since there was no protocol part specified, we guess what protocol it
   * is based on the first letters of the server name.
   */

  /* Note: if you add a new protocol, please update the list in
   * lib/version.c too! */

  if(checkprefix("FTP.", conn->host.name))
    protop = "ftp";
  else if(checkprefix("DICT.", conn->host.name))
    protop = "DICT";
  else if(checkprefix("LDAP.", conn->host.name))
    protop = "LDAP";
  else if(checkprefix("IMAP.", conn->host.name))
    protop = "IMAP";
  else if(checkprefix("SMTP.", conn->host.name))
    protop = "smtp";
  else if(checkprefix("POP3.", conn->host.name))
    protop = "pop3";
  else {
    protop = "http";
  }

**Comment by rabsym** [comment]
Feel free to use or delete this PR for helping other with docs.

https://github.com/jsuto/mailpilerorg-site/pull/4

**Comment by jsuto** [comment]
Thank you for updating the docs!
