### ISSUE TITLE
Problem viewing emails after upgrading

### ISSUE THREAD

**Issue by dabuv** [jsuto/piler#23]
I recently upgraded Piler to version 1.3.12, build 1001, as well as sphinx to version 3.3.1.

First I upgraded piler to 1.3.10 and reindex’ed everything successfuly, and run delta-index.sh scripts. I had the same problem with webUI, where there were no emails like shown on attached screenshot:
![msedge_8QBTUnNfB7](https://github.com/jsuto/piler/assets/61107486/8f1f9e32-6ebe-4e81-a58e-adf78e5e0a95)

I thought that it might be version problem so I upgraded to version 1.3.10 and 1.3.11 I ended up with 1.3.12.

Here is example of how I upgraded Piler:
```
wget https://bitbucket.org/jsuto/piler/downloads/piler-1.3.12.tar.gz
tar -xzf piler-1.3.12.tar.gz
cd piler-1.3.12
./configure --localstatedir=/var --with-database=mysql
make
su -c 'make install'
ldconfig
```

I really hoped that upgrading sphinx to 3.3.1 and reindexing everything will solve the issue but I still struggled with the same problem.

I upgraded Sphinx following instruction in Bitbucket Issue https://bitbucket.org/jsuto/piler/issues/1299/users-mails-are-not-shown-in-the-gui-ldap 

After searching for logs I found this in /var/log/maillog:

```
Apr 28 18:45:09 archive piler-webui[5473]: unknown local index 'main1' in search request
Apr 28 18:45:09 archive piler-webui[5473]: sphinx query: 'SELECT id FROM main1,dailydelta1,delta1 WHERE        MATCH('') ORDER BY `sent` DESC LIMIT 0,50 OPTION max_matches=1000' in 0.00 s, 0 hits, 0 total found
```

The sphinx directory (/var/piler/sphinx) has all the required files with piler:piler permissions. I checked database by connecting to it via

mysql -P9306 --protocol=tcp --prompt='sphinxQL> ' -u piler
but I could not view databases or tables - it was visible when connecting to standard mariadb instance which directory expanded after using “reindex -a”. 

So i restarted my instance and the problem with "unknown index" vanished, but I still see "Empty search result" when logging in to piler

Did I miss anything? Any help would be greatly appreciated

**Comment by jsuto** [comment]
For starters, let's verify that you have some index data after the reindex. Run the following:

```
mysql -h0 -P9306
show tables;
```

I have the following tables on my test env:

```
MySQL [(none)]> show tables;
+--------+------+
| Index  | Type |
+--------+------+
| note1  | rt   |
| piler1 | rt   |
| tag1   | rt   |
+--------+------+
```

Verify that you can see the index tables, the run the below statement to verify that it has some data:

```
show index <TABLE_NAME> status;
```

You should see something similar like (though I use RT index, not plain)

<img width="397" alt="image" src="https://github.com/jsuto/piler/assets/5683354/cada95be-7f47-4bf3-acf6-1045fc196f69">

**Comment by dabuv** [comment]
I revieved table on my restored backup of instance and on the old one what You asked looks like this:
![image](https://github.com/jsuto/piler/assets/61107486/4e300144-f209-44b7-899e-d89bd6a98268)

While my upgraded installation looks like this:
![image](https://github.com/jsuto/piler/assets/61107486/9819360f-7a0e-46a6-a6ff-7635279142d8)

**Comment by jsuto** [comment]
The problem is that the sph_index table is not getting processed. The indexer.delta.sh script should process its content, then delete afterwards. Check if user piler's crontab entries are in place, then as user piler run the indexer.delta.sh script, and finally check if sph_index table has 0 rows.

**Comment by dabuv** [comment]
1. I ran indexer.delta.sh yesterday twice. Can I debug it somehow? There is no output on ending when running it manually in screen session
2. Did you check what i posted about differences between table structure? Is it normal in my case?
3. I checked the table, it only has one row with random ID (checked with SELECT * FROM sph_index LIMIT 5)

Thanks for Your time!

**Comment by jsuto** [comment]
Yes, I noticed, and above I told you that I use RT index. Anyway, run the below command as user piler and look for any issues it reports:

```
indexer --config /etc/piler/manticore.conf delta1
```

**Comment by dabuv** [comment]
Here is the output:
![image](https://github.com/jsuto/piler/assets/61107486/9445098a-dc62-4529-af89-06a16804c983)

**Comment by jsuto** [comment]
OK, that's something. But I wonder, how is it possible that you have a single email in sph_index table while the mysql table on this is 52 GB?

**Comment by dabuv** [comment]
That is a very good question. Let me revision what my upgrade path looked like. 
I started with Piler version 1.3.3 and Sphinx 2.2. I upgraded from piler 1.3.3 to 1.3.9 because I had issues importing emails using "pilerimport" tool because of old tls used by it. Version 1.3.9 worker like a charm.

Then I realized that that I can't see any emails on webUI, so I tried reindexing without any success and I thought that maybe upgrading to 1.3.12 will solve the issue but nope I was still in the same place. So last in the queue was upgrading Sphinx because I saw You recommending it in some threads on Bitbucket, but that still didn't help.

Every upgrade of piler looked like this:
```
wget https://bitbucket.org/jsuto/piler/downloads/piler-1.3.12.tar.gz
tar -xzf piler-1.3.12.tar.gz
cd piler-1.3.12
./configure --localstatedir=/var --with-database=mysql
make
su -c 'make install'
ldconfig
```

Sphinx upgrade looked like the procedure proposed by B.JEGADEESAN on Bitbucket Issue https://bitbucket.org/jsuto/piler/issues/1299/users-mails-are-not-shown-in-the-gui-ldap (with changing user/password of course)

Additionally my original crontab of piler user looks like this (which i didn't modify)
```
#5,35 * * * * /usr/local/libexec/piler/indexer.delta.sh
#30   2 * * * /usr/local/libexec/piler/indexer.main.sh
#15,45 * * * * /usr/local/libexec/piler/indexer.attachment.sh
#*/15 * * * * /usr/bin/indexer --quiet tag1 --rotate --config /usr/local/etc/piler/sphinx.conf
#*/15 * * * * /usr/bin/indexer --quiet note1 --rotate --config /usr/local/etc/piler/sphinx.conf
30   6 * * * /usr/bin/php /usr/local/libexec/piler/generate_stats.php --webui /var/piler/www >/dev/null
#*/5 * * * * /usr/bin/find /var/piler/www/tmp -type f -name i.\* -exec rm -f {} \;
#0 */4 * * * /var/piler/cron/cron-import.sh  > /dev/null 2>&1
```
(the hashes are from time of upgrade procedure)

Maybe some version had major changes that I missed?

**Comment by dabuv** [comment]
I eventually restored backup and upgraded directly to 1.3.11 (although the tag is 1.3.10) and not version by version. Everything works fine now. Anyway thanks for trying to point me in right direction yesterday.
