### ISSUE TITLE
imapfetch.py fails with password related encoding error

### ISSUE THREAD

**Issue by thorstenspille** [jsuto/piler#25]
**Describe the bug**
imapfetch.py exits with exception, when '€' is used in password and the import whole import fails.

**To Reproduce**
1. Go to https://piler.example.com/index.php?route=import/list
2. Insert an imap-ssl account with € in the password
3. A click on "Test connection"  will return OK
4. After adding there will be no progress
5. Checked it manually via cli as the piler user and run {libexecdir}/piler/import.sh, result is in the screenshot section.

**Expected behavior**
The import script should be able to handle any password. If one mailbox fails, the script should continue with other configured mailboxes.

**Screenshots**
~~~
piler@archiv:~$ /usr/libexec/piler/import.sh 
~/imap ~
~/imap ~/imap
Traceback (most recent call last):
  File "/usr/libexec/piler/imapfetch.py", line 230, in <module>
    main()
  File "/usr/libexec/piler/imapfetch.py", line 201, in main
    conn.login(user, password)
  File "/usr/lib/python3.11/imaplib.py", line 610, in login
    typ, dat = self._simple_command('LOGIN', user, self._quote(password))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/imaplib.py", line 1230, in _simple_command
    return self._command_complete(name, self._command(name, *args))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/imaplib.py", line 987, in _command
    arg = bytes(arg, self._encoding)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode character '\u20ac' in position 5: ordinal not in range(128)

~~~

**Piler version:**
 - 1.4.4

**Additional context**

**Notes**
If sensitive data is required to understand the situation, then don't copy it to the issue, rather send it to my address (see piler -V output)

**Comment by jsuto** [comment]
I think it's a bug in imaplib, see https://github.com/python/cpython/issues/93548 and https://github.com/python/cpython/pull/29398/files#diff-5997ba238d8d6b18687e9a70f2bc2c6df796fbfee1ab9fcbd33dae4144192faf

Try the following fix. Edit /usr/lib/python3.11/imaplib.py and add the following function around the 617th line somewhere between ```def login(self, user, password):``` and ```def login_cram_md5(self, user, password):```

Notes: the original and still open PR used the first lambda, however a reviewer suggested the 2nd lambda. Let me know which works better.

```
    def login_plain(self, user, password):
        """Authenticate using PLAIN SASL mechanism.
        This is a plain-text authentication mechanism that can be used
        instead of login() when UTF-8 support is required.
        """
        return self.authenticate(
            "PLAIN",
            #lambda _: "{0}\x00{0}\x00{1}".format(user, password).encode()
            lambda _: f'\x00{user}\x00{password}'.encode('utf-8')
        )
```

Then edit imapfetch.py, and apply the following diff:

```
diff --git a/util/imapfetch.py b/util/imapfetch.py
index fb5f2fb..433f403 100755
--- a/util/imapfetch.py
+++ b/util/imapfetch.py
@@ -198,7 +198,7 @@ def main():
         conn.authenticate("XOAUTH2", lambda x: generate_auth_string(
             user, opts['access_token']))
     else:
-        conn.login(user, password)
+        conn.login_plain(user, password)
 
     conn.select()
```

**Comment by thorstenspille** [comment]
Hi Janos,
thank you for the fast response.
In my case both of the lambda functions are working, but I ended up using the suggested second lambda.
I've added a fixed version of the imaplib module to /usr/libexec/piler, to overide the os provided module.

**Comment by jsuto** [comment]
Great, I'll make a note for it
