### ISSUE TITLE
[BUG] The auditor cannot restore emails

### ISSUE THREAD

**Issue by stephdl** [jsuto/piler#29]
**Describe the bug**
Well not sure it is a bug, or a misconfiguration of my piler instance or something I did not understand on the role of auditor@local

**To Reproduce**
- I installed piler from your container for NethServer
- the code is available [here](https://github.com/NethServer/ns8-piler)
- once everything is up and configured, I can use the user to reach the archive, read its email and restore them, so far no error, I could even see the activity inside the journald events

```
May 06 12:53:22 d1.deb12-pve.org dovecot[4226]: imap(stephane)<2265><LyzE4MYXdrwKBQQB>: save: box=Sent, uid=9, msgid=<f26d5e1a3173eda1dd9b9bfa6373e144@deb12-pve.org>, from=stephane@deb12-pve.org, subject=dfdsf, flags=()
May 06 12:53:22 d1.deb12-pve.org samba-dc[2020]: TLS ../../source4/lib/tls/tls_tstream.c:1378 - Decryption has failed.
May 06 12:53:22 d1.deb12-pve.org dovecot[4226]: imap(stephane)<2265><LyzE4MYXdrwKBQQB>: save: box=Sent, uid=10, msgid=<0a24aadd6f21547dcf8cafbaea4fddb6@deb12-pve.org>, from=stephane@deb12-pve.org, subject=Re: dfdsf, flags=()
May 06 12:53:22 d1.deb12-pve.org samba-dc[2020]: TLS ../../source4/lib/tls/tls_tstream.c:1378 - Decryption has failed.
May 06 12:53:22 d1.deb12-pve.org samba-dc[2020]: TLS ../../source4/lib/tls/tls_tstream.c:1378 - Decryption has failed.
May 06 12:53:22 d1.deb12-pve.org dovecot[4226]: imap(stephane)<2265><LyzE4MYXdrwKBQQB>: save: box=Sent, uid=11, msgid=<9a23047de117c4a323c44a3910beb66f@deb12-pve.org>, from=stephane@deb12-pve.org, subject=Re: dfdsf, flags=()
May 06 12:53:22 d1.deb12-pve.org dovecot[4226]: imap(stephane)<2265><LyzE4MYXdrwKBQQB>: save: box=Sent, uid=12, msgid=<29a3f7403dcc0a39a73b38abd416dc75@deb12-pve.org>, from=stephane@deb12-pve.org, subject=Re: dfdsf, flags=()
May 06 12:53:22 d1.deb12-pve.org dovecot[4226]: imap(stephane)<2265><LyzE4MYXdrwKBQQB>: Disconnected: Logged out in=2495 out=859 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
```

- when I use the auditor@local, I can see the email of users, search inside, but when I select emails and I press the button restore, I see no errors, nothing in the log of the server and obviously no restoration

**Expected behavior**
I expect that the auditor is able to restore the emails of a user

this is the [config-site.php](https://github.com/NethServer/ns8-piler/blob/main/imageroot/templates/config-site.php) file that I use

The question I have is how the auditor@local could restore because it is not allowed to imap, nor postfix in my configuration. I did a tour of your documentation but for now I do not have a clue

**Screenshots**

**Piler version:**
```
root@d1:~# runagent -m piler3 podman exec piler-app piler -V
piler 1.4.4, build 1001, Janos SUTO <sj@acts.hu>

Build Date: Wed Mar 22 13:59:43 UTC 2023
ldd version: ldd (Ubuntu GLIBC 2.35-0ubuntu3.1) 2.35
gcc version: gcc version 11.2.0 (Ubuntu 11.2.0-19ubuntu1) 
OS: Linux d4b9dee07b72 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Configure command: ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-database=mariadb 
MySQL client library version: 3.3.8
Extractors: /usr/bin/pdftotext /usr/bin/catdoc /usr/bin/catppt /usr/bin/xls2csv /usr/bin/unrtf /usr/bin/tnef libzip
```

**Comment by stephdl** [comment]
Reading https://github.com/jsuto/piler/blob/bf28ea314b127086a5275b121a1fdeb4466c1d3b/webui/controller/message/bulkrestore.php#L90

For what I understand is that when you are auditor you do not restore by imap but you restore by smtp. Do I am wrong ?
I need to set a smarthost to piler to allow auditor to restore  the email in bulk or individually

**Comment by stephdl** [comment]
True

adding 
```
$config['SMARTHOST'] = '10.5.4.1';
$config['SMARTHOST_PORT'] = 25;
$config['SMARTHOST_USER'] = '';
$config['SMARTHOST_PASSWORD'] = '';
```

I can restore by smtp but the limitation I face is I send to the INBOX of the user, even if it should go to the SENT folder, with IMAP this is correctly handled

BTW we are close to release piler for NethServer 8 :p 

I think we could close this issue, my instance was not fully configured

**Comment by jsuto** [comment]
Awesome news :-)
