### ISSUE TITLE
Please support subpath

### ISSUE THREAD

**Issue by th-2021** [jsuto/piler#35]
I want to use https://my-host/mail to access piler and I haven't found an easy way to implement it.
(I'm using kubernetes and nginx-ingress as proxy)

**Comment by jsuto** [comment]
Why a dedicated hostname is not OK?

**Comment by th-2021** [comment]
I'm running all services on a single host. Running with subpath eases this.    

Am 10. Mai 2024 12:29:15 MESZ schrieb jsuto ***@***.***>:

**Comment by jsuto** [comment]
You can assign several dns names to a single host as well.

**Comment by jsuto** [comment]
As currenly I'm reworking the gui to support bootstrap 5, I can see that the current path is hardwired at many code lines. Let's postpone this until the rewrite is complete.

**Comment by jsuto** [comment]
Started to work on this feature
