### ISSUE TITLE
[BUG] Error messages during pilerimport

### ISSUE THREAD

**Issue by th-2021** [jsuto/piler#40]
Usind docker image 1.4.5.

During pilerimport (imap) I'm getting errors:

Syntax Error: Can't get Fields array<0a>
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table

What is the issue here?

Also some folders are missing:

processed:    5712 [ 73%]
processing folder: Archives/2023... ERROR: select cmd error:
processing folder: INBOX... ERROR: select cmd error:
processing folder: Entw&APw-rfe... ERROR: select cmd error:
processing folder: Trash... ERROR: select cmd error:

Why is this happening?

**Comment by jsuto** [comment]
If a message has attachment(s), then the parser runs external utilities to extract the textual data to index. Occasionally these external helpers have a hard time to do their job, and they print some warnings like you mentioned. It's safe to ignore them.

**Comment by th-2021** [comment]
These are error messages. And some folders are completely missing (second half of the issue)

**Comment by th-2021** [comment]
I tried util/imapfetch.py and got this result:
Error processing folder "Apple\ Mail\ To\ Do"
Error processing folder "Sent\ Messages"
Processed 17278 messages

pilerimport read: 
received messages | 5,676

**Comment by jsuto** [comment]
What kind of imap server do you have?

**Comment by th-2021** [comment]
That's the server info duing connect:

fetchmail: SSL/TLS: using protocol TLSv1.3, cipher TLS_AES_256_GCM_SHA384, 256/256 secret/processed bits
fetchmail: IMAP< * OK [CAPABILITY IMAP4rev1 CHILDREN ENABLE ID IDLE LIST-EXTENDED LIST-STATUS LITERAL- MOVE NAMESPACE SASL-IR SORT SPECIAL-USE THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN AUTH=LOGIN AUTH=PLAIN] IMAP server ready H migmx010 28.0 IMAP-1M4Kyh-1s5mGb2Luj-000MUx

**Comment by th-2021** [comment]
When I run pilerimport again, it's finishing silently very fast. Is there some kind of timestamp? Or why is it not running again?

**Comment by jsuto** [comment]
I assume, it's not your imap server. Try running it with verbose mode so that it prints all the folders.
Also what happens if you run it on a single imap folder?

```pilerimport .... -f "Sent Messages"```
```pilerimport .... -f "Sent\ Messages"```

Does either of them succeed?

**Comment by th-2021** [comment]
With -f I could import the remainder of the folders. So all folders succeed.

**Comment by jsuto** [comment]
You may also give imapfetch.py a try. It might perform better to download emails from the imap server, and then you can run pilerimport to import emails from the local directory.
