### ISSUE TITLE
[BUG] Docker Update 1.4.4 ---> 1.4.5 does not work

### ISSUE THREAD

**Issue by simatec** [jsuto/piler#62]
I have a [Github project](https://github.com/simatec/piler-docker) where I can install and update the Piler with an installer. The whole thing in combination with ngnix and Letsentcryt.

There are always problems when updating to a new version.
Currently the update from 1.4.4 to 1.4.5 does not work.

What should I bear in mind when updating Docker? Normally, the containers should only be rolled out again and nothing should be tinkered with in the individual files.

However, Piler is very special here.

Which files need to be edited or deleted in the volumes when updating the Docker container?

Translated with DeepL.com (free version)

**Comment by jsuto** [comment]
Please clarify what doesn't work, give me context to understand the issue.

**Comment by simatec** [comment]
The following error message appears in the piler log

`rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Permission denied.
rsyslogd: activation of module imklog failed [v8.2112.0 try https://www.rsyslog.com/e/2145 ]`

The webui does not start in the browser and displays the following error

`Error: SQLSTATE[HY000] [2002] Connection refused on database: sphinx`

**Comment by jsuto** [comment]
Are there any manticore logs to see why it can't start?

**Comment by simatec** [comment]
Unfortunately, the log doesn't give anything else... That's why I suspect that files have changed in v1.4.5, but are already present in the volumes from v1.4.4.

Here is the log from Manticore

````
DEBUG: mysql is ready
DEBUG: metadata table exists
 * Starting periodic command scheduler cron
   ...done.
 * Starting nginx nginx
   ...done.
rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Permission denied.
rsyslogd: activation of module imklog failed [v8.2112.0 try https://www.rsyslog.com/e/2145 ]
starting searchd . . .
[Mon Jun  3 10:22:30.068 2024] [74] using config file '/etc/piler/manticore.conf' (10594 chars)...
Manticore 6.3.0 1811a9efb@24052209 (columnar 2.3.0 88a01c3@24052206) (secondary 2.3.0 88a01c3@24052206) (knn 2.3.0 88a01c3@24052206)
Copyright (c) 2001-2016, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
Copyright (c) 2017-2024, Manticore Software LTD (https://manticoresearch.com)

starting daemon version '6.3.0 1811a9efb@24052209 (columnar 2.3.0 88a01c3@24052206) (secondary 2.3.0 88a01c3@24052206) (knn 2.3.0 88a01c3@24052206)' ...
listening on 127.0.0.1:9312 for sphinx and http(s)
listening on 127.0.0.1:9306 for mysql
Manticore 6.3.0 1811a9efb@24052209 (columnar 2.3.0 88a01c3@24052206) (secondary 2.3.0 88a01c3@24052206) (knn 2.3.0 88a01c3@24052206)
Copyright (c) 2001-2016, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
Copyright (c) 2017-2024, Manticore Software LTD (https://manticoresearch.com)

precaching table 'main1'
precaching table 'main2'
precaching table 'main3'
precaching table 'main4'
precaching table 'dailydelta1'
precaching table 'delta1'
precaching table 'tag1'
precaching table 'note1'
Manticore 6.3.0 1811a9efb@24052209 (columnar 2.3.0 88a01c3@24052206) (secondary 2.3.0 88a01c3@24052206) (knn 2.3.0 88a01c3@24052206)
Copyright (c) 2001-2016, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
Copyright (c) 2017-2024, Manticore Software LTD (https://manticoresearch.com)

starting piler-smtp . . .
starting piler . . .
````

**Comment by jsuto** [comment]
So, manticore is running, check if it listens on both 127.0.0.1:9306 and 9307. If not on 9307, then fix manticore.conf based on manticore.conf.dist file.

**Comment by simatec** [comment]
Is this a breaking change in 1.45?

**Comment by simatec** [comment]
I understand that very well. Thanks for the explanation. 
I'm just wondering whether it might be possible to take such changes into account in the Dockerfile in the future and check them. 

In the Docker world, many people simply update using Portainer, for example, and unfortunately this doesn't always work with Piler. 

Do you have any idea how to take such changes into account and check them in the Dockerfile?

**Comment by jsuto** [comment]
Well, I personally believe that you need to understand what a certain upgrade means, and what changes it introduces. In general you just can't upgrade that everything keeps working. Sometimes database schemas are updated, new configuration variables are added, etc. that you need to be aware of. That's what the changelogs and release notes are for.

Anyway, I'll give it a thought how to make a docker upgrade more convenient.

**Comment by simatec** [comment]
I have now installed a [patch](https://github.com/simatec/piler-docker/blob/bd4fc495d1bfba2e3e8081265939960fc93a8aef/patch.sh#L79) for the listen entry in manticore.conf during the update.

I fixed the kernel error for rsyslog in the [Dockerfile](https://github.com/simatec/piler-docker/blob/bd4fc495d1bfba2e3e8081265939960fc93a8aef/build/Dockerfile#L48)

**Comment by simatec** [comment]
In addition, I have added the [environment](https://github.com/simatec/piler-docker/blob/bd4fc495d1bfba2e3e8081265939960fc93a8aef/config/piler-ssl.yml#L42) to migrate to the new MariaDB version
