### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by 3D-Vie-Tom** [jsuto/piler#68]
To install piler on a system with MySQL 8 or higher the script to add a user must be fixed.

tilll you start "make postinstall" the installer try to add a user for the piler system.

MySQL has end the support to create a user with Version 8 with grant command.

piler-piler-1.4.5

so you have to change the script in ./util/db-mysql-root.sql.in 
change the grant line to create user and a grant line.

"create database MYSQL_DATABASE character set 'utf8mb4';
create user 'MYSQL_USERNAME'@'localhost' IDENTIFIED BY 'MYSQL_PASSWORD';
grant all privileges on MYSQL_DATABASE.* to MYSQL_USERNAME@localhost WITH GRANT OPTION;
flush privileges;"

**Comment by 3D-Vie-Tom** [comment]
MySQL has end the support to create a user with Version 8 with grant command !

**Comment by 3D-Vie-Tom** [comment]
After fixing that issue, 
more and more problems are coming up.

make postinstall have a lots of problems on a ubunto 22.04 or 24.04 not only with mysql 8.
Sphinx makes a lot of problems. 

In the install guide in the first line, 
"Debian and Ubuntu users please see the [FAQ](https://www.mailpiler.org/faq) to avoid a common pitfall, and fix /etc/default/sphinxsearch before start using sphinx." but i cant find Sphinx related FAQ on your system.
Maybe here is my problem located. 

> WARNING: key 'read_timeout' is deprecated in 
> /usr/local/etc/piler/sphinx.conf line 219; use 'network_timeout'
> instead.
> WARNING: key 'max_children' was permanently removed from configuration. 
> Refer to documentation for details.
> WARNING: key 'preopen_indexes' is deprecated in 
> /usr/local/etc/piler/sphinx.conf line 223; use 'preopen_tables'
> instead.
> WARNING: key 'workers' is deprecated in 
> /usr/local/etc/piler/sphinx.conf line 226; use 'default value' instead.
> FATAL: failed to open '/var/piler/sphinx/binlog.lock': 2 'No such file 
> or directory'

this is cause, because no folder /var/piler/sphinx was created.
After create it manually, sphinx try to open files, but this files are located at /var/piler/manticore.

so i made a sym link from manticore to sphinx, then other problems poping up.
No database sphinx ...

**Comment by jsuto** [comment]
Not good. Piler 1.4.5 features manticore, as the preferred search engine. The postinstall.sh script should have ```SEARCHCFG="${PILER_CONFIG_DIR}/manticore.conf"``` as the default.

**Comment by jsuto** [comment]
I've just fixed the postinstall on the master branch (https://github.com/jsuto/piler/archive/refs/heads/master.zip).
Please start over (drop the piler mysql database, remove /var/piler and /usr/local/etc/piler dirs) and install this release, and you should be fine.

**Comment by 3D-Vie-Tom** [comment]
Hi

 

Ill have tried from skratch and it works.

Exapt the MySQL8 deprecated createing user with grant option.

 

Thanks for your great help.

 

 

 

Von: jsuto ***@***.***> 
Gesendet: Samstag, 8. Juni 2024 07:51
An: jsuto/piler ***@***.***>
Cc: 3D-Vie-Tom ***@***.***>; Author ***@***.***>
Betreff: Re: [jsuto/piler] [BUG] (Issue #68)

 

I've just fixed the postinstall on the master branch (https://github.com/jsuto/piler/archive/refs/heads/master.zip).
Please start over (drop the piler mysql database, remove /var/piler and /usr/local/etc/piler dirs) and install this release, and you should be fine.
