### ISSUE TITLE
[BUG] Custom functions: Issue with PHP 8.2

### ISSUE THREAD

**Issue by FanDjango** [jsuto/piler#70]
Using the current github master I have managed*) to install, import all mails and use the GUI successfully.

*) This was not possible using the plain 1.4.5 release. The postinstall.sh changes made a big difference.

I migrated from a PILER on a Debian 9 (stretch) to this here Debian 12 (bookworm) - piler V1.4.5 master cadc0ac6861f856f61aa53a156676657afb2835c

In the previous system I was making use of a custom function:

```
$config['CUSTOM_EMAIL_QUERY_FUNCTION'] = 'my_custom_func';

function my_custom_func($username = '') {
   $session = Registry::get('session');
   $data = $session->get("auth_data");

   $a = array();

   foreach($data['emails'] as $email) {
      $s = explode("@", $email);
      array_push($a, $s[0] . "@redacted.com");
      array_push($a, $s[0] . "@redacted.de");
      array_push($a, $s[0] . "@evenmoreredacted.de");
   }

   $data['emails'] = array_merge($data['emails'] , $a);

   $session->set("auth_data", $data);
}
```

This causes the GUI to fail (500) and a PHP error to be reported in the nginx error log:

```
2024/06/11 14:18:36 [error] 1046#1046: *39 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /usr/local/etc/piler/config-site.php:31
```

Trying to debug this, I seem to find that even $session and $data are not being correctly set. Does this have anything to do with PHP 8.2 which is default on Debian bookworm?

**Comment by jsuto** [comment]
What's exactly in line 31?

**Comment by FanDjango** [comment]
`foreach($data['emails'] as $email) {` is that line.

`'emails'` is not set, I tried a var_dump.

The user that is logging on has got emails (more than one) set in the GUI admin config.

I tried a var_dump of $data, there is nothing. Nor is there anything inside $session when this function is called.

The error occurs after entering the email address and the password on the login.php page.

```
2024/06/11 18:03:50 [error] 1052#1052: *257 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /usr/local/etc/piler/config-site.php:51
Stack trace:
#0 /var/piler/www/model/user/auth.php(132): my_custom_func()
#1 /var/piler/www/model/user/auth.php(49): ModelUserAuth->checkFallbackLogin()
#2 /var/piler/www/controller/login/login.php(48): ModelUserAuth->checkLogin()
#3 /var/piler/www/system/front.php(36): ControllerLoginLogin->index()
#4 /var/piler/www/system/front.php(14): Front->execute()
#5 /var/piler/www/index.php(113): Front->dispatch()
#6 {main}
  thrown in /usr/local/etc/piler/config-site.php on line 51
```

It is now line 51, because I have added other stuff in the meantime above in the `config_site.php`.

If I comment out the `$config['CUSTOM_EMAIL_QUERY_FUNCTION'] = 'my_custom_func';`, all is ok (but I don't get the desired effect of the custom function, of course.

I had a look in the calling functions (`checkFallbackLogin()`), and thought about var_dumping in there to see more, but wanted to ask **first** if PHP 8. was a potential problem **or if you had an initial thought** about what could be causing this.

**Comment by jsuto** [comment]
So you use a local account to login when you run into the issue. Let me test it in my dev env, it uses PHP 8.3.

**Comment by jsuto** [comment]
I've troubleshooted the issue, and the fix is twofold:

a) simplify the custom func

```
$config['CUSTOM_EMAIL_QUERY_FUNCTION'] = 'my_custom_func';

function my_custom_func($username = '') {
   $emails = array();

   $s = explode("@", $username);

   $emails[] = $s[0] . "@redacted.com";
   $emails[] = $s[0] . "@redacted.de";
   $emails[] = $s[0] . "@evenmoreredacted.de";

   return $emails;
}
```

b) fix model/user/auth.php (I'll create a PR soon with the fix)

```
diff --git a/webui/model/user/auth.php b/webui/model/user/auth.php
index 26af4a39..eecf681e 100644
--- a/webui/model/user/auth.php
+++ b/webui/model/user/auth.php
@@ -129,7 +129,7 @@ class ModelUserAuth extends Model {
          $data['auditdomains'] = $this->model_user_user->get_users_all_domains($query->row['uid']);
 
          if(CUSTOM_EMAIL_QUERY_FUNCTION && function_exists(CUSTOM_EMAIL_QUERY_FUNCTION)) {
-            call_user_func(CUSTOM_EMAIL_QUERY_FUNCTION, $username);
+            $data['emails'] = call_user_func(CUSTOM_EMAIL_QUERY_FUNCTION, $username);
          }
          else {
             $data['emails'] = $this->model_user_user->get_users_all_email_addresses($query->row['uid']);
```

**Comment by FanDjango** [comment]
@jsuto I confirm that this fix has resolved the issue, tested it just now. Thx.
