### ISSUE TITLE
[BUG] "Table 'dailydelta1': cannot apply kill list to myself". Install issue.

### ISSUE THREAD

**Issue by kirillhilfiger** [jsuto/piler#73]
Hello, I have tried to install piler, 1.4.5 and 1.4.4 release. Went through the guide on https://www.mailpiler.org/installation/ and at the postinstall got the error below. Tried to change this config file, but it didn't help.

![1](https://github.com/jsuto/piler/assets/59509414/3e1511a7-38e7-4d09-b05e-a6156ba469f7)

Below is the part of manticore.conf, that is causing the problem.

![image](https://github.com/jsuto/piler/assets/59509414/3fc0227f-7790-40ee-9bd3-b29cca748e4e)

**Comment by jsuto** [comment]
This issue has been fixed on the master branch (soon to be 1.4.6). Please download the master branch, and start over.
