### ISSUE TITLE
[BUG] Connection refused on database: sphinx or how to upgrade docker?

### ISSUE THREAD

**Issue by federtechnik** [jsuto/piler#75]
**Describe the bug**
I have a running docker version 1.4.3 and tried to upgrade to version 1.4.5 but the webinterface shows only Connection refused on database: sphinx

Can you please tell me the correct way to upgrade a docker installation? I could not find anything about it in the documentation

**Comment by jsuto** [comment]
Check out the release notes: https://github.com/jsuto/piler/blob/piler-1.4.5/RELEASE_NOTES. See the sections for 1.4.4 and 1.4.5.

Also edit /etc/piler/manticore.conf, and add the following line to the searchd { } at the end:

```
listen                  = 127.0.0.1:9307:mysql_readonly
```

**Comment by federtechnik** [comment]
Thank you for this fast answer!

I'm sorry for not ready the release notes ... 🫣

I have to try it later and will comme back if it doesn't work.

**Comment by jsuto** [comment]
No worries, I'm here to help.
