### ISSUE TITLE
Migration from bare metal piler 1.1.1 to docker

### ISSUE THREAD

**Issue by gabviv73** [jsuto/piler#77]
Hy,
is it possible ?

**Comment by jsuto** [comment]
Well, sort of. Version 1.1.1 is more ancient than Earth :-) So, assuming that you have an empty archive running in docker, the easiest (though not the fastest) solution would be to export all emails from old archive, and import them to new archive.

**Comment by gabviv73** [comment]
So: pilerexport and  pilerimport ?
Is it possible to import directly from the filesystem reading the old installation archives using only a pileimport run ?

**Comment by jsuto** [comment]
You may copy the files and piler related configs from the filesystem, then probably fix some paths, also copy the mysql data. And then modify each sql table to match the schemas in https://github.com/jsuto/piler/blob/master/util/db-mysql.sql

**Comment by jsuto** [comment]
No further update.

**Comment by gabviv73** [comment]
I'm doing the migration to a new docker stack via simple pilerexport and  pilerimport.
It's a pain. So much space needed ...
