### ISSUE TITLE
FATAL: table 'dailydelta1': cannot apply kill list to myself

### ISSUE THREAD

**Issue by elarrexo** [jsuto/piler#78]
**Describe the bug**
When run make postinstall, I show this message "FATAL: table 'dailydelta1': cannot apply kill list to myself:", and execution stop

**To Reproduce**
1. ln -s /usr/local/etc/piler/manticore.conf /usr/local/etc/piler/sphinx.conf
2. touch /usr/local/etc/piler/MANTICORE
3. make postinstall
4. FATAL: table 'dailydelta1': cannot apply kill list to myself
5. drop piler DB
6. edit manticore, delete line 132 killlist_target         = main1:kl, main2:kl, main3:kl, main4:kl, dailydelta1:kl
7. make postinstall create tables.

**Expected behavior**
By removing line 132 from the manticore.conf file, will it affect piler in the future?

**Piler version:**
 - "piler -V" output
piler 1.4.5
ubuntu 22.04

**Notes**
If sensitive data is required to understand the situation, then don't copy it to the issue, rather send it to my address (see piler -V output)

**Comment by jsuto** [comment]
Again, this issue is fixed in latest master.
