### ISSUE TITLE
[BUG] <Blank GUI environment when mencache is enabled>

### ISSUE THREAD

**Issue by elarrexo** [jsuto/piler#79]
**Describe the bug**
When I enabel memcache the GUI environment show blank/empty

**To Reproduce**
1. set $config['MEMCACHED_ENABLED'] = 1; on config-site.php
2. (nginx) - error.log see error  "2024/06/24 13:56:29 [error] 3478#3478: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught ArgumentCountError: Memcached::add() expects at most 3 arguments, 4 given in /var/piler/www/model/saas/customer.php:122
Stack trace:
#0 /var/piler/www/model/saas/customer.php(122): Memcached->add()
[#1](https://bitbucket.org/jsuto/piler/issues/1/this-is-a-test-issue) /var/piler/www/controller/common/menu.php(20): ModelSaasCustomer->get_customer_settings_by_email()
[#2](https://bitbucket.org/jsuto/piler/issues/2/2-test-issue) /var/piler/www/system/controller.php(47): ControllerCommonMenu->index()
[#3](https://bitbucket.org/jsuto/piler/issues/3/wrong-save-button) /var/piler/www/controller/common/layout.php(18): Controller->render()"
3. Edith and change /var/piler/www/model/saas/customer.php "$memcache->add($cache_key, array('data' => serialize($data)), 0, MEMCACHED_TTL); -> $memcache->add($cache_key, array('data' => serialize($data)), MEMCACHED_TTL);"

**Expected behavior**

**Screenshots**

**Piler version:**
 - "piler -V" output
piler 1.4.5, Janos SUTO <sj@acts.hu>

Build Date: Mon Jun 24 13:41:51 UTC 2024
ldd version: ldd (Ubuntu GLIBC 2.35-0ubuntu3.8) 2.35
gcc version: gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) 
OS: Linux piler.filtanet.tech 5.15.0-112-generic #122-Ubuntu SMP Thu May 23 07:48:21 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Configure command: ./configure --localstatedir=/var --with-database=mariadb --enable-memcached
MySQL client library version: 3.3.10
Extractors: /usr/bin/pdftotext /usr/bin/catdoc /usr/bin/catppt /usr/bin/xls2csv /usr/local/bin/ppthtml /usr/bin/unrtf /usr/bin/tnef libzip 

**Notes**
Does changing this setting affect the functionality of piler?

**Comment by jsuto** [comment]
Install the latest master (soon to be 1.4.6), it fixes this problem.
