### ISSUE TITLE
Message list appears as loading

### ISSUE THREAD

**Issue by artyck** [jsuto/piler#80]
Hello, i have just installed mailpiler on an Ubuntu 24 machine.
It is running, i can login, create users.
I created an import task, that finished correctly as far as i can tell.
Despite this, the message list stays empty and shows "loading". I have waited for a possible re-index but nothing.
I have also modified the config file with "define('RT', 1);" for it to be "realtime" but nothing changes.

Something i did wrong?

![mailpiler finished](https://github.com/jsuto/piler/assets/170518508/f6552871-de0d-4269-be5a-9f16fe199a78)
![mailpiler loading](https://github.com/jsuto/piler/assets/170518508/e2d51d3e-a64b-4269-93f3-466bc599a155)

**Comment by jsuto** [comment]
Try hitting the red search button. Also note that user admin is usually not supposed to search for emails. Regular users or auditors should. Also make sure that the RT settings in manticore.conf, config.php and piler.conf are consistent.

**Comment by artyck** [comment]
It was not the build/config side of the program itself but rather a user/domain configuration problem, it is now sorted.
Thank you for for your help, it pointed me in the right direction.
