### ISSUE TITLE
[BUG] Bulk Downlaod Selected Emails giving a 404 not found error

### ISSUE THREAD

**Issue by gkwurst** [jsuto/piler#81]
I have the Piler installed and working with our old emails after the migration (Piler 1.4.5).  I can restore emails to mailboxes via Smartpost, restore to the original mailbox, and download individually as an .eml.  If I select any number of emails and click on Bulk Download Selected Emails I get a 404 not found page from nginx and the URL http://piler.mydomain.com/bulkrestore.php in the URL bar.  Anything I need to look at here?

**Comment by jsuto** [comment]
Verify that you have the following rewrite rule in piler-nginx.conf:

```rewrite /bulkrestore.php /index.php?route=message/bulkrestore;```

**Comment by gkwurst** [comment]
The problem was file ownership of the /var/piler/www directory.  On install it was set as root:root.  Changing to www-data:www-data resolved the issue with not finding the bulkrestore.php file.

It did not resolve my other issue with saving the user settings, though.  Still getting a 500 error when trying to save.  Page is also display 2 fields for number of items per page for some reason.
![piler_settings](https://github.com/jsuto/piler/assets/63482205/ea78de9d-a1a4-45e7-b986-b572ea11e559)

**Comment by jsuto** [comment]
Well, then don't change it to be owned by www-data. Not sure what the reason was for that in the first place.
