### ISSUE TITLE
[BUG] Archived mails are empty, downloaded files are 0 bytes

### ISSUE THREAD

**Issue by thorstenspille** [jsuto/piler#84]
Hi Janos,
for our project zamba-lxc-toolbox (https://github.com/bashclub/zamba-lxc-toolbox) I've build a deb package to install and configure mailpiler community automatically on debian bookworm.
The deb package is built on our gitlab community server https://gitlab.bashclub.org/bashclub/piler/ and is hosted on https://apt.bashclub.org.
Based on the information provided in the installation guide https://www.mailpiler.org/installation/ and the postinstall script https://github.com/jsuto/piler/blob/master/util/postinstall.sh.in I've built the deb package to install and configure mailpiler with dependencies on the system automatically.
Almost everything works fine, but archived email content not displayed in the WebUI (via auditor@local) and download links produce 0 byte files.

**To Reproduce**
1. Navigate to the mailpiler WebUI
2. Login as auditor@local
3. Click on one mail in the list
4. Only Date, From, To and Subject of the mails are displayed, Mails are completely empty, downloads links only produce empty files.

**Expected behavior**
Email body should be displayed, files should be downloadable.

**Piler version:**
piler 1.4.5, Janos SUTO <sj@acts.hu>

Build Date: Sun May 26 13:32:40 CEST 2024
ldd version: ldd (Debian GLIBC 2.36-9+deb12u7) 2.36
gcc version: gcc version 12.2.0 (Debian 12.2.0-14) 
OS: Linux gitlab-runnner 6.5.11-7-pve #1 SMP PREEMPT_DYNAMIC PMX 6.5.11-7 (2023-12-05T09:44Z) x86_64 GNU/Linux
Configure command: ./configure --prefix=/usr --localstatedir=/var --sysconfdir=/etc --with-database=mysql --enable-memcached --enable-clamd --enable-compat-layout
MySQL client library version: 3.3.8
Extractors: /usr/bin/pdftotext /usr/bin/catdoc /usr/bin/catppt /usr/bin/xls2csv /usr/bin/unrtf /usr/bin/tnef libzip

**Comment by jsuto** [comment]
Hello Thorsten,

please verify that pilerget is setuid/setgid to piler user and group, also check the ```$config['DECRYPT_BINARY']``` value in either /var/piler/www/config.php or in (I guess) /etc/piler/config-site.php that it points to the proper path.

**Comment by jsuto** [comment]
_pilerget executable and $config['DECRYPT_BINARY'] seems to be okay_

Well, it's not. Run chmod 4755 /usr/bin/pilerget, and try again.

_www-data is member of the group piler_

It shouldn't be. That's why piler* binaries are setuid/setgid. Please check the Makefile in the src dir, and make sure you install the binaries just like that.

**Comment by thorstenspille** [comment]
Ah, now I understand. After years of Linux, I never cared about the special file permissions.
```
chmod 4775 /usr/bin/pilerget
```
That's the solution.

Thank you very much for your help!

**Comment by jsuto** [comment]
Great! Don't forget to fix pileraget as well (the gui uses it to download a single attachment).
