### ISSUE TITLE
manticore calls manticore-buddy as user piler and it fails mkdir /usr/local/lib/manticore/buddy-plugins

### ISSUE THREAD

**Issue by dilyanpalauzov** [jsuto/piler#86]
I followed the installation instrutctions for piler with manticore.  /var/piler/manticore/manticore.log says that mkdir() fails from BUDDY.  Running everything as user piler and the provided pilersearch.service for Systemd.

When I execute this as user piler, buddy fails to mkdir nticore/buddy-plugins .

**Comment by jsuto** [comment]
Show me the full path for the buddy-plugins dir.

**Comment by dilyanpalauzov** [comment]
The invocation is 

> /usr/share/manticore/modules/manticore-buddy/bin/manticore-buddy --listen=http://127.0.0.1:9312 --bind=127.0.0.1  --threads=6 --skip=manticoresoftware/buddy-plugin-sharding --skip=manticoresoftware/buddy-plugin-queue

and the full path is `/usr/local/lib/manticore/buddy-plugins/`

**Comment by dilyanpalauzov** [comment]
It puts in this directory a composer.json file with content `{"minimum-stability":"dev"}` and that is all.

**Comment by jsuto** [comment]
Try setting the buddy_path variable, see https://manual.manticoresearch.com/Server_settings/Searchd#buddy_path

**Comment by dilyanpalauzov** [comment]
I have created the folder manually.  What I am saying is, that the configuration does not work out of the box.
