### ISSUE TITLE
systemd/pilersearch: /run/piler has to be created differently in 1.4.6

### ISSUE THREAD

**Issue by dilyanpalauzov** [jsuto/piler#95]
I had configured executing `./configure && make install` with ansible for version 1.4.5.  After I upgraded to 1.4.6 I expected everytihng will work.  It turns out, that the provided file https://github.com/jsuto/piler/blob/master/systemd/pilersearch.service:
```
[Service]
ExecStart=/usr/bin/searchd --config /etc/piler/manticore.conf
ExecStartPre=/bin/bash -c "if [[ ! -d /var/run/piler ]]; then mkdir -p /var/run/piler; chown piler:piler /var/run/piler; fi"
ExecStop=/usr/bin/searchd --config /etc/piler/manticore.conf --stopwait
PIDFile=/var/run/piler/searchd.pid
KillMode=process
Restart=on-failure
RestartPreventExitStatus=255
Type=forking
User=piler
```
cannot create as user=piler the directoy /var/run/piler.  Howevet it turned out that replacing the line
> ExecStartPre=/bin/bash -c "if [[ ! -d /var/run/piler ]]; then mkdir -p /var/run/piler; chown piler:piler /var/run/piler; fi"

with
> RuntimeDirectory=piler

fixed it!

Beside, on start pilersearch logs a warning

Supervising process
650 which is not out child. We'll most likely not notice when it exits.

and process 650 is `/usr/bin/searchd --config /usr/local/etc/plier/manticore.conf` which has as child process manticoresearch-buddy-manager.

**Comment by jsuto** [comment]
Thanks for the fix, I'm running the related PR.

**Comment by dilyanpalauzov** [comment]
When I start piler, it logs:

Aug  1 14:40:11 hostname piler-smtp[512]: reloaded config: /usr/local/etc/piler/piler.conf
Aug  1 14:40:11 hostname piler-smtp[512]: ERROR: could not create directory: */var/run/piler*
Aug  1 14:40:10 hostname piler-smtp[512]: piler-smtp 1.4.6 starting
Aug  1 14:40:10 hostname piler[513]: ERROR: could not create directory: */var/run/piler*
Aug  1 14:40:10 hostname piler[513]: piler 1.4.6 starting
Aug  1 14:40:10 hostname piler[549]: cannot write pidfile: /var/run/piler/piler.pid
Aug  1 14:41:40 hostname piler[1756]: piler 1.4.6 starting

so probably the line `RuntimeDirectory=piler` is missing from the other two files, too.  The files in syslog are indeed in inversed chronological order: 14:40:11 is before 14:40:10.  This probably means that first piler failed to set /var/run/piler/piler.pid and then the systemd-unit for pilersearch created /var/run/piler.

**Comment by dilyanpalauzov** [comment]
Uf, pilersearch.service had RuntimeDirectory=piler and the other two .service files did not have it.  As they run as User=piler they cannot create /var/run/piler, this has to be created by RuntimeDIrectory=piler.

**Comment by dilyanpalauzov** [comment]
Oh, no, I am wrong. Sorry for writing to much.

piler-smtp.service and piler.service contain User=root . If all three services write in /var/run/piler, one service runs as user piler, the other services run as user root, and I see no order in the service files, for me it is unclear which service is supposed to be started first, to create /var/run/piler/ and set the owner as `piler`.
