### ISSUE TITLE
Render SVG image in email preview

### ISSUE THREAD

**Issue by vmario89** [jsuto/piler#96]
Hi, using piler 1.4.5 SVG images are not rendered in Email preview. I checked for available settings and mime types at config level and also at the nginx config dir. Also got no browser console errors.

It seems to be that piler just ignores SVGs in mails. They occure when downloading as *.eml and viewing them externally. When using PDF export the SVG is also missing.

is there any way to get it displayed?

thank you very much

**Comment by vmario89** [comment]
thanks for pushing that! i tried it out but there are not images in preview_pane in total. it seems i am missing something. is there any config about this? i double-checked the permissions in /var/piler/www already for tmp/ and images/ - played with chmod 777 and owner piler:piler

**Comment by jsuto** [comment]
When clicking on a message that has an svg file, check what you have in /var/piler/www/tmp, there should be a file named as i.<attachment id>.svg, eg. i.544.svg

**Comment by vmario89** [comment]
i changed to piler:www-data but still a lot of images are just not rendered and are also not exported by PDF then. but they exist in the *.eml file

i think this is always the case when the image comes from external URL source. eg. is not rendered:
```
                            moz-do-not-send="true"><img
src="https://www.epiloglaser.com/dist_site/sales-updates/images/facebook-60.png"
                              alt="alt_text"
style="-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;-ms-interpolation-mode: bicubic;"
                              moz-do-not-send="true" width="60"
                              height="99" border="0"></a> </td>
```

my browser does not work about CORS or other things, so it might be a bug in piler which ignores just the URLs

**Comment by vmario89** [comment]
embedded images are working in piler
