### ISSUE TITLE
Missing IMAP TLS option in Webgui

### ISSUE THREAD

**Issue by vmario89** [jsuto/piler#98]
Hi, the import of mails with Piler Web GUI does not work in all cases. There is missing an option to use TLS instead of SSL or plain auth.

when i change "SSL" to "TLS", my connection is working properly. We need an option or checkbox to reflect this.
https://github.com/jsuto/piler/blob/a14961d2b102a45fe1924ca2c6f1c1f07b301ae1/webui/controller/import/test.php#L54C1-L54C26

its the same thing like setting in config-site.php in /etc/piler. i had to discover this because it it not documented ( i think)

```
$config['IMAP_RESTORE_FOLDER_INBOX'] = 'INBOX';
$config['IMAP_RESTORE_FOLDER_SENT'] = 'Sent';
$config['IMAP_HOST'] = 'mail.somehost.de';
$config['IMAP_PORT'] = 143;
$config['IMAP_SSL'] = 'TLS';
```

**Comment by vmario89** [comment]
added PR https://github.com/jsuto/piler/pull/99

**Comment by jsuto** [comment]
Thanks for the PR.
